### ISSUE TITLE
Legends Quest issues

### ISSUE THREAD

**Issue by Amarolyth** [Zoinkwiz/quest-helper#1000]
Running through this quest it felt like the helper was always out of sync and didnt know where to take me. Pretty much had to use the wiki for every bit of the quest. I would try to state where exactly it wasn't working but I can assure you it was for every part of the quest.

**Comment by Zoinkwiz** [comment]
This should hopefully be resolved with https://github.com/Zoinkwiz/quest-helper/commit/7c8b242cba956635480a9b22b641505fb068d033.
