### ISSUE TITLE
Prince Ali Rescue Step Error

### ISSUE THREAD

**Issue by CIeetZ** [Zoinkwiz/quest-helper#1008]
Hi. In Prince Ali Rescue the quest asked me to talk to Leela while carrying all the required items ie. beers wig paste rope skirt . However I was supposed to talk to Osman first and I had to go do that before Leela.

**Comment by Zoinkwiz** [comment]
This should be resolved now with https://github.com/Zoinkwiz/quest-helper/commit/d587bf5185d05fc944c41581d01381dbec4a162a
