### ISSUE TITLE
The Slug Menace - Lumbridge Graveyard teleport was removed from game

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1015]
In the recommended items list, the note on the Water Altar teleport shows the Lumbridge Graveyard as the best option. [This teleport no longer exists in the game](https://oldschool.runescape.wiki/w/Lumbridge_Graveyard_Teleport), this note needs to be deleted.

**Comment by rheine15** [comment]
This quest should also be updated as [Ring of the Elements](https://oldschool.runescape.wiki/w/Ring_of_the_elements) is now the best form of teleport to all the elemental altars.
