### ISSUE TITLE
Lair of Tarn Razorlor (miniquest) - add highlight and note to avoid the receding walls

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1018]
The receding walls will push you to the level below and cause a big headache while trying to get to Tarn's Lair. Add a highlight to the tiles that need to be sprinted past, and add a descriptor to the side-bar step.

Old step: "Follow the path to the east."
New step recommendation: "Follow the path to the east. Search the wall traps in the first hallway. Sprint past the receding walls on the narrow ledge one at a time just after they recede.

![image](https://user-images.githubusercontent.com/38710634/210004067-e77ef4fe-6482-44dc-bf36-999312699044.png)
![image](https://user-images.githubusercontent.com/38710634/210004469-cb45a725-1b8a-4ce2-892e-02cdccc0eee9.png)

**Comment by zahti** [comment]
Same update should be applied to the **Terror Dog** task in the Morytania Medium Diary:
![image](https://user-images.githubusercontent.com/38710634/212146051-bfcd4ff4-2e25-4b93-b6eb-4215816cf072.png)

**Comment by LucasMolander** [comment]
+1 please do this, I had an annoying time getting knocked off the ledge

**Comment by Zoinkwiz** [comment]
This should be resolved with https://github.com/Zoinkwiz/quest-helper/commit/b689ec35e4190fbaea10abe78adff59e3659c0ae.
