### ISSUE TITLE
Digsite Quest broken

### ISSUE THREAD

**Issue by ScrupyPup** [Zoinkwiz/quest-helper#1026]
Every other quest i've used the plugin for previously has worked fine but multiple times during digsite the plugin got suck on a step that I had already completed and at one point even jumped back couple of steps (to panning for special cup which i had already done and handed in)

**Comment by Zoinkwiz** [comment]
https://github.com/Zoinkwiz/quest-helper/commit/1da9d6d8d6e57c294d6b200c78f133575618f662 should hopefully help fix this for prolific spacebarrers.
