### ISSUE TITLE
Hard Lumbridge Diary - Rename 'Duel Arena' to 'PvP Arena'

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1028]
Description for the **Smite Altar** task needs to be updated, it is still using the old name:
Rename the _Duel Arena_ to _PvP Arena_

**Comment by Frosty-J** [comment]
The task diary refers to it as the Emir Arena in-game, though the map, world names and Grouping interface all call it the PvP Arena. Newsposts also refer to it as the PvP Arena more commonly than Emir's Arena, though the wiki's chosen name for it is Emir's Arena. Sorry for the tangent - I was weighing up if PvP Arena is the name to use, and I think it is.
