### ISSUE TITLE
Same update should be applied to the **Terror Dog** task in the Morytania Medium Diary:

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1031]
Same update should be applied to the **Terror Dog** task in the Morytania Medium Diary:
![image](https://user-images.githubusercontent.com/38710634/212146051-bfcd4ff4-2e25-4b93-b6eb-4215816cf072.png)

_Originally posted by @zahti in https://github.com/Zoinkwiz/quest-helper/issues/1018#issuecomment-1380805323_

**Comment by Zoinkwiz** [comment]
This should be resolved with https://github.com/Zoinkwiz/quest-helper/commit/b689ec35e4190fbaea10abe78adff59e3659c0ae
