### ISSUE TITLE
Quest Helper Causing Stuttering in Client

### ISSUE THREAD

**Issue by YeetViberson** [Zoinkwiz/quest-helper#1040]
For some reason, the quest helper now causes a persistent stuttering within the Runelite client when a quest is selected. When the quest is deselected, the stutter immediately goes away. This is a new problem, popped up in the past two weeks or so. Unable to figure out a solve.

**Comment by YeetViberson** [comment]
It’s any quest. It disappeared yesterday but is back today, making me think it’s an issue with my computer not being able to handle that plug-in plus OBS running at the same time. But I’m happy to share my runelite logs, how do I go about doing that?On Jan 18, 2023, at 12:17 PM, Zoinkwiz ***@***.***> wrote:﻿
Hey @YeetViberson , does this happen for a specific quest, or all quests? Could you also please share your Runelite logs so I can see if anything is happening there.

**Comment by Zoinkwiz** [comment]
On Windows, open your file explorer and in the bar where it says 'Quick Access' or 'Documents' along the top, simply paste in:
%userprofile%.runelite\logs

On Linux and Mac OS, you can use cd:
cd $HOME/.runelite/logs
