### ISSUE TITLE
Incomplete steps for 'Murder Mystery'

### ISSUE THREAD

**Issue by Superfluxus** [Zoinkwiz/quest-helper#1059]
When using the Quest Helper plugin for the quest 'Murder Mystery', the plugin only directs you to complete 2 of the 3 steps.

The plugin will direct you to

 - Pickup the Criminal's Dagger
 - Pickup the Pungent Pot
 - Investigate the broken window
 - Talk to the Gossip
 - Talk the the Poison Seller
 - Talk to Carol
 -  Investigate the Drain
 - Turn in quest with the Guard

It wasn't until I consulted the Wiki that I found that I had to also:

- Get the fingerprints from the dagger using Flour and Paper
- Search Carol's room for her bottle
- Get fingerprints from the bottle
- Compare the fingerprints so they match

THEN you can turn the quest in.

**Comment by valarauca** [comment]
I also encountered this issue recently.

**Comment by Zoinkwiz** [comment]
Should be resolved in https://github.com/Zoinkwiz/quest-helper/commit/70ce053116a357a885407dd5b38cb093bc80ac28
