### ISSUE TITLE
Add quests in the order of the optimal quest guide?

### ISSUE THREAD

**Issue by Poltergeisen** [Zoinkwiz/quest-helper#106]
I'm a fairly new player and I'm running through quests using this guide:
https://oldschool.runescape.wiki/w/Optimal_quest_guide

It would be a nice-to-have to implement new quests in this order to make it easier to get my quests points higher.

Thanks for the amazing work on this plugin!

**Comment by MathGeniusJodie** [comment]
would be super dope

**Comment by lesteenman** [comment]
I'm currently working through the ironman version of that guide, and I want to try adding quests I encounter that are missing.

**Comment by Zoinkwiz** [comment]
This is now added, and you can sort by optimal.
