### ISSUE TITLE
Lunar Diplomacy memory markers

### ISSUE THREAD

**Issue by tbloody** [Zoinkwiz/quest-helper#1062]
I think it would be useful to have markers on the tiles that you fell through in the memory challenge. (or of the tiles you successfully stood on)

PS: how could I collaborate? I would like to write this addition to the quest helper if possible. I am a software developer but have 0 experience with runelite plugins.

**Comment by Zoinkwiz** [comment]
Currently it should remember the spots you've gone on which are correct, but it seems to be bugged. Not sure what is from a glance, The code is in https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/quests/lunardiplomacy/MemoryChallenge.java, so if you can spot anything wrong with it please do feel free to make a PR 😄

**Comment by Zoinkwiz** [comment]
Should be fixed now with https://github.com/Zoinkwiz/quest-helper/commit/14a9c8f16513c4151fd0351babf567cbcd2af502.

**Comment by tbloody** [comment]
nice :) 
didn't get around to looking at it, life got in the way.
