### ISSUE TITLE
Swan Song - Add Recommended items

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1064]
Please add these to the recommended item list:

- 1 x Draynor Village teleport (Amulet of Glory)
- 2 x Piscatoris teleport
- 1 x Yanille teleport (Nightmare Zone minigame teleport or Watchtower teleport)
- 1 x Crafting guild teleport (Skills Necklace)
- 1 x Cooking gauntlets (to reduce the chance of burning the 5 Monkfish caught during the quest)

#### Starting off

- 1 x Piscatoris teleport
- 1 x Draynor Village teleport (Amulet of Glory)

#### Entering the colony

- 1 x Piscatoris teleport

#### Helping Arnold

- 1 x Cooking gauntlets (to reduce the chance of burning the 5 Monkfish caught during the quest)

#### Making an army

- 1 x Yanille teleport (Nightmare Zone minigame teleport or Watchtower teleport)
- 1 x Crafting guild teleport (Skills Necklace)

**Comment by tbloody** [comment]
I also noticed I need a brown apron to enter the crafting guild, so that should probably be in the requirements as well. (in the "Making an Army" step)

**Comment by Zoinkwiz** [comment]
Thanks for the breakdown, made it a lot easier to implement 😄
