### ISSUE TITLE
Watchtower questhelper stops

### ISSUE THREAD

**Issue by tbloody** [Zoinkwiz/quest-helper#1068]
the questhelper stops right after talking to the wizard after returning the fingernails

EDIT: tried to continue with wiki and seems to restart at 'learn the skavid language' didn't check earlier.

**Comment by dylanwe** [comment]
Did it not tell you to look in the in game quest menu for it to sync again?

**Comment by tbloody** [comment]
No, I tried closing and opening quest helper, but I didn't think of looking in quest helper

**Comment by Zoinkwiz** [comment]
I'm hoping https://github.com/Zoinkwiz/quest-helper/commit/1da9d6d8d6e57c294d6b200c78f133575618f662 will improve the dialog detection considerably to avoid it breaking, so fingers crossed this is resolved now.
