### ISSUE TITLE
Hazeel Cult - Missing step

### ISSUE THREAD

**Issue by ZenVee** [Zoinkwiz/quest-helper#1069]
During the quest, if you side with Ceril, when you get to the point of killing Almone, you do not pick up the armor from him, you must search the chest in the room which is where you get the armor. This confused me and I had to check the wiki to figure it out.

https://i.imgur.com/TAx3Fsk.png

Thanks for the awesome plugin though :)

**Comment by wvanderp** [comment]
+1

**Comment by johnyuki** [comment]
Doing this quest now and it is still missing.
