### ISSUE TITLE
Incorrect ordering for "optimal" quest ordering

### ISSUE THREAD

**Issue by Mistah210** [Zoinkwiz/quest-helper#1072]
Hi,

I noticed today that Secrets of the North is listed as my next quest in the "optimal" ordering tab, however it requires Making Friends with My Arm, General's Shadow, and Devious Minds as pre-reqs, which I have not completed yet and are further down the "optimal" ordering.

Thanks for making such a great tool!

**Comment by michaelcmelton** [comment]
+1

**Comment by TwiggyLeo** [comment]
I am also having this issue.

**Comment by Zoinkwiz** [comment]
Should be fixed now https://github.com/Zoinkwiz/quest-helper/commit/a06567e8a64091d78cd96784e01a9ef606733ca7
