### ISSUE TITLE
Easy Kandarin streamlining

### ISSUE THREAD

**Issue by dovry** [Zoinkwiz/quest-helper#1087]
Doing easy kandarin tasks along the guide has you running back and forth around Seers/Catherby quite a bit.

Here's my re-ordered list, you start in Catherby and make your way towards the coal trucks, completing each task as you run east -> west

https://oldschool.runescape.wiki/w/Kandarin_Diary#Easy

\1. Catch a mackerel at Catherby.
\8. Get a pet fish from Harry in Catherby.	
\2. Buy a candle from the candle maker in Catherby. 	
\10. Speak to Sherlock between the Sorcerer's Tower and Keep Le Faye.
\3. Collect 5 flax from the Seers' Village flax field.
\4. Play the Church organ in the Seers' Village church.
\9. Buy a stew from the Seers' Village pub. 	
\7. Defeat one of each elemental in the Elemental Workshop.
\5. Plant jute seeds in the farming patch north of McGrubor's Wood. 	
\6. Have Galahad make you a cup of tea (found in the house west of McGrubor's Wood).
\12. Cross the Coal truck log shortcut.

**Comment by dovry** [comment]
![image](https://user-images.githubusercontent.com/15201298/222679271-47dcc1e0-84c3-4f08-8ef5-1ed3a345e8e2.png)

**Comment by andersenalan** [comment]
I'll attempt these cahnges
