### ISSUE TITLE
Devious Minds Quest Helper does not detect orb in pouch

### ISSUE THREAD

**Issue by BardurFarder** [Zoinkwiz/quest-helper#1091]
On the "gift for entrana" step, quest helper does not move on to the next step after filling the large rune pouch with the orb even after checking the pouch and using the orb directly on the pouch.

**Comment by Zoinkwiz** [comment]
fixed with https://github.com/Zoinkwiz/quest-helper/commit/8cb3b02ae294a44c959746e78b384d490d6640f2
