### ISSUE TITLE
Desert Medium Diary 

### ISSUE THREAD

**Issue by neddul** [Zoinkwiz/quest-helper#1105]
In the Desert Medium Diary, the item requirements say that you need 1x Scroll of redirection, but that is wrong. The achievement says to enter your house from Pollnivneach. 
The requirement should say something like "have your house in Pollnivneach" etc..

**Comment by wyvern800** [comment]
true

**Comment by Auenc** [comment]
I suspect this is an issue with Runelite not detecting unranked group ironmen.
