### ISSUE TITLE
Missing steps in quest: Watchtower

### ISSUE THREAD

**Issue by timwaldron** [Zoinkwiz/quest-helper#111]
The steps to steal the rock cake are skipped in the watchtower quest

![image](https://user-images.githubusercontent.com/47076570/102007740-c62e5c00-3d7f-11eb-9175-aca3693acb70.png)

**Comment by Zoinkwiz** [comment]
Hi, the step exists and should work from what I can see. What was the progression you saw, just entering the gate, then straight away 'go talk to the guard'?

**Comment by timwaldron** [comment]
So the steps it told me were to hand over the relic at the first gate, then it instantly went to jump the bridge with "20 coins" in your inventory, skipping getting the rock cake for the next barrier.

Sorry I should have gotten a screenshot of that to explain a bit better.

**Comment by Zoinkwiz** [comment]
Hi @timwaldron I've tested this out and it seems this is one of the few cases during the quest where it's using a variable value to determine whether you've given a rock cake already, and if so it'll then say to go over the bridge, and it seemed to work for me. Is it possible you'd already given the guard a rock cake prior to entering the city with the guide on? If not I'm a bit stumped unless the varbits can be representing different things for different people, but I've not encountered a quest doing that before now.

**Comment by timwaldron** [comment]
@Zoinkwiz Sorry for the late reply. I don't recall ever stealing/giving the rock cake to the guard before this quest. The only thing I can think of that may have messed it up for me is that I gave one troll a gold bar trying to complete a clue scroll prior to starting this quest. Unsure if that has anything to do with it.

This was the location where I paid the gold bar. I still remember having to complete that step in the quest though
![image](https://user-images.githubusercontent.com/47076570/103144109-1215d380-4778-11eb-859b-db788ef68080.png)

**Comment by Zoinkwiz** [comment]
This should now be fixed with https://github.com/Zoinkwiz/quest-helper/commit/42fbec986645dbbdafb905eb2d4618802c29917e
