### ISSUE TITLE
Ratcatchers Quest Missing How To Get Snake Charm

### ISSUE THREAD

**Issue by Andrew-Cunningham** [Zoinkwiz/quest-helper#1110]
In the "Helping Felkrash" step you need to obtain the snake charm but there is not instructions on how to obtain the snake charm. You have to add another coin to the Snake Charmer pot after talking to him to get the snake charm.

**Comment by Zoinkwiz** [comment]
The step in the sidebar says 'Use a coin on the pot next to the Snake Charmer in Pollnivneach.', and highlights the dialog options you need to click to get the charmer. Did that not happen for you @Andrew-Cunningham ?
