### ISSUE TITLE
Knight Waves incomplete in diaries

### ISSUE THREAD

**Issue by Frosty-J** [Zoinkwiz/quest-helper#1116]
Knight Waves is displayed as incomplete in the Kandarin Hard Diary, even though I've done it. I don't think Morytania Hard is affected, but I can't be certain as I've already completed it. This is problematic because it prevents the diary from ever showing up in the list when filtered by "Show Meets Reqs".

![Screenshot of Knight Waves complete in Quest Helper](https://user-images.githubusercontent.com/60154347/232244651-084b0b30-0eab-4c52-8661-c99c4da8012e.png)|![Screenshot of Knight Waves incomplete in Kandarin Hard](https://user-images.githubusercontent.com/60154347/232244661-61f0a2f6-7b1b-4b32-8d11-f19583db5f4a.png)

https://github.com/Zoinkwiz/quest-helper/blob/fbc3447f9f736e8ab290209c0cdb41db71c22089/src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinHard.java#L295-L304

**Comment by Zoinkwiz** [comment]
This should be fixed with 2fc6c1228a6a27621311edc74c9aefd11c7b9a58
