### ISSUE TITLE
External Resources section not resetting

### ISSUE THREAD

**Issue by BenKelenski** [Zoinkwiz/quest-helper#1122]
After using the quest helper for _Dragon Slayer II_ I then selected _Secrets of the North_ and scrolled down to the `External Resources` which still says "Dragon Slayer II Wiki" and links to the respective wiki guide. I tried hitting the "X" in the top-right of the panel and reselecting _Secrets of the North_ again and the incorrect wiki guide still shows.
![quest_helper_bug](https://user-images.githubusercontent.com/26673501/233757635-20faa223-7994-42a2-9943-c23316ece952.PNG)

**Comment by Zoinkwiz** [comment]
This should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/ab20ae3296c4837b873fc62e02f8809a27187ffb
