### ISSUE TITLE
murder mystery

### ISSUE THREAD

**Issue by Haydenh1201** [Zoinkwiz/quest-helper#1127]
not working

**Comment by hydraware** [comment]
Can confirm broken when I was completing it two ago. Continued completion through the official wiki.

**Comment by Zoinkwiz** [comment]
This should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/70ce053116a357a885407dd5b38cb093bc80ac28, hopefully the changes should be merged in to the live plugin over the coming days.
