### ISSUE TITLE
Check all Items, Spade tooltip missing Ernest the Chicken

### ISSUE THREAD

**Issue by Sylphoid** [Zoinkwiz/quest-helper#1128]
![image](https://user-images.githubusercontent.com/42817257/234100335-30f84416-e05a-4d0f-a513-3b0c3dfc6f2b.png)

In the long list of requirements, Spade is required to search the compost heap, but it doesn't show up on the tooltip.

**Comment by Zoinkwiz** [comment]
I believe that during the helper you're told to get the spade from within the mansion itself rather than beforehand. Would you imagine items marked as 'obtainable during quest' should be included in the all items helper?

**Comment by Sylphoid** [comment]
I didn't realize that the helper step says to grab a spade during the quest. I had believed that the all items list would be comprehensive to include non-quest items that are used, but taking another look, does the tooltip remove quests that I have already completed?

**Comment by Zoinkwiz** [comment]
It should remove completed quests yeah.
