### ISSUE TITLE
Throne of miscellania

### ISSUE THREAD

**Issue by Lexthegayotter** [Zoinkwiz/quest-helper#1130]
Quest helper is locked into marrying the princess with a male character, despite the fact that you can choose which one you want to wed, causes some issues because of the different process depending on which one you want to wed

**Comment by Zoinkwiz** [comment]
This should be resolved with https://github.com/Zoinkwiz/quest-helper/commit/b689ec35e4190fbaea10abe78adff59e3659c0ae#diff-67fa8fbb61c8f974a94825b7cde1b4fcc63c6fd58b0dee473d463080026edcb3.
