### ISSUE TITLE
Enhancement to add achievement diaries as well

### ISSUE THREAD

**Issue by Poltergeisen** [Zoinkwiz/quest-helper#115]
I think it would be awesome if this addon (or another similar one) could help to do achievement diaries as well.

Ideally it'd list the skills, quests, and items required to get these diaries and would help you find each npc and guide you to where to complete each task.

Thanks again for the wonderful addon!

**Comment by Spiffyriffic** [comment]
I've been thinking this stuff since I got the plugin. Well put :)

**Comment by Zoinkwiz** [comment]
I'd like to add this, as well as some almost path systems which help players go for common goals, for example 'Path to Barrows gloves', 'Path to Priffdinnas', etc.

For Achievements, how I'd personally imagine it is it'd let you know what items you need for the various tasks you can currently do, then go through them in an order dictated by size of task + proximity of tasks.

**Comment by Zoinkwiz** [comment]
Work on achievement diaries is now happening so I'll close this issue and open achievement-specific issues where necessary.
