### ISSUE TITLE
Catalytic Talisman can be used instead of Death Talisman in ME2 quest

### ISSUE THREAD

**Issue by Sergen94** [Zoinkwiz/quest-helper#1164]
The Catalytic Talisman/Tiara can be used on the death altar in the quest Mournings End. This is very helpful for ironman as its fairly easy to obtain it from the Guardians of the Rift minigame to bypass the 50 items shopping list for those IM who do not have the death talisman.

**Comment by SpencerSKane** [comment]
Although not explicitly stated in the guide, a catalytic talisman is set as an alternate item for the death talisman within the code.
