### ISSUE TITLE
"Mogres have layers" in Falador Medium Diary doesn't have arrow on map nor mini map

### ISSUE THREAD

**Issue by DaMage93** [Zoinkwiz/quest-helper#1213]
It does show where to throw the explosive if you can see the spot, but it doesn't have an arrow showing on the mini map nor the map

**Comment by Zoinkwiz** [comment]
Fixed in https://github.com/Zoinkwiz/quest-helper/commit/dae6d8d53a653a7f9bf5b9b8039c48407f73f4c5
