### ISSUE TITLE
Demon Slayer stuck.

### ISSUE THREAD

**Issue by LilyMods** [Zoinkwiz/quest-helper#1221]
Demon slayer is stuck thinking I have completed Rovins and Prysins keys when I havent even started the quest yet. This means it also doesn't remember the correct incantation as it thinks it already has seen it.

**Comment by Zoinkwiz** [comment]
Hey @LilyMods was this when doing Quest Speedrunning, or in the real game?

**Comment by LilyMods** [comment]
I believe it was while Speed running
