### ISSUE TITLE
suggestion: "reveal solution" button in side bar before actually giving puzzle answers

### ISSUE THREAD

**Issue by VladiMatt** [Zoinkwiz/quest-helper#1222]
I love this plugin for stuff like SOTE where the whole friggin library just SUCKS, but then doing DT2 recently without a guide at all was actually really satisfying. I'd like to suggest a config option that "pauses" the quest helper before giving you the answer to puzzles, just to give you a moment to try to figure it out for yourself. Then the side bar would have a "reveal solution" button to unpause and continue the helper in case you get stuck or simply refuse to do the stupid 4 hour light beam puzzle dungeons in SOTE or MEP2.

While it's always possible to manually enable/disable the plugin or even just the quest hint settings, this would streamline the process a good bit and I know there's gotta be at least two other users who would appreciate that lmao

**Comment by Zoinkwiz** [comment]
Currently got a PR up to add a filter option for puzzles https://github.com/Zoinkwiz/quest-helper/pull/1444.
