### ISSUE TITLE
Lumbridge & Draynor Hard Diary - Power Amulet location off

### ISSUE THREAD

**Issue by DaMage93** [Zoinkwiz/quest-helper#1240]
The first step says to "Move to the Lumbridge smithy." However, the arrow is pointing to the pub in Lumbridge. If you go to the smithing  tutor location, the arrow then changes to the correct location.

**Comment by Zoinkwiz** [comment]
Fixed in https://github.com/Zoinkwiz/quest-helper/commit/26d2adad0a5106f9fa10b713499a9a52357d283a.
