### ISSUE TITLE
Monkey Madness II QOL request

### ISSUE THREAD

**Issue by IMI4tth3w** [Zoinkwiz/quest-helper#125]
Hello!

First of all, thank you for all the work on this plugin. It really is an absolute game changer.

Next, my request is pretty simple. While doing Kruk's agility dungeon, there are 5 sections. If you fail an obstacle you fall into a pit of maniacle monkeys. 4 of these "sections" have monkeys that attack melee, but one of the sections has ranged monkeys. The quest guide does correctly show what to pray, but the change from pray melee to pray ranged when moving from section 3 to section 4 is very hard to notice.

I don't have any specific suggestions to improve this, but if there was a better way to let the player know they need to pray ranged instead of melee during that 4th section that would be amazing! (and yes, I did die here lol)

Other than that, I'm just eagerly awaiting the "Song of the Elves" guide!

Thank you!

**Comment by Zoinkwiz** [comment]
Hey, I've tried to make it clearer with changes in https://github.com/Zoinkwiz/quest-helper/commit/ad9c662b15100d39ac5bfa9eaf34bdf69eb36df6, so hopefully the caps text and red/green text once you fall will help.
