### ISSUE TITLE
Error in displayed rewards for Watchtower quest

### ISSUE THREAD

**Issue by JoeErani** [Zoinkwiz/quest-helper#1258]
For the test watchtower the reward lists 5000 x 5000 coins instead of just 5000 coins as shown in the screenshot below.
![image](https://github.com/Zoinkwiz/quest-helper/assets/11185464/18b66df9-c6f9-46d9-902f-ba46e6cd30d7)

**Comment by IanMcNelly** [comment]
Fixed by #1256
