### ISSUE TITLE
Quest helper tries to set config values before the user is logged in, leads to warning spam

### ISSUE THREAD

**Issue by MosheBenZacharia** [Zoinkwiz/quest-helper#1259]
not sure what the consequences are of this but here are the logs:

[questhelper.log](https://github.com/Zoinkwiz/quest-helper/files/12570910/questhelper.log)

**Comment by sufferfish** [comment]
Can you give the steps on how to recreate this?

**Comment by MosheBenZacharia** [comment]
this happens every time I launch from IntelliJ with plugin hub enabled. I got the full logs by logging an exception here:

<img width="645" alt="image" src="https://github.com/Zoinkwiz/quest-helper/assets/12495920/4154a874-a836-48b5-ba12-82c9a3e900ed">

**Comment by MosheBenZacharia** [comment]
looks like it will be resolved by https://github.com/Zoinkwiz/quest-helper/commit/21edb557f9008df2c732a4643c04256f4bd2ecdc
