### ISSUE TITLE
The Giant Dwarf progression problems

### ISSUE THREAD

**Issue by alexanderfrancis** [Zoinkwiz/quest-helper#127]
There are a couple of instances within The Giant Dwarf quest guide where the flashing blue arrows indicating to talk to an NPC will not progress until after you've already moved on and completed the next step.

One particular example of this is when you need to talk to the Librarian in Keldagrim. After you talk to him and select the proper chat options, you need to find a book in one of the bookshelves, but the quest helper will be stuck telling you to keep talking to the Librarian.

Great work on the plugin so far!

**Comment by Zoinkwiz** [comment]
https://github.com/Zoinkwiz/quest-helper/commit/7a8c2f570fde189c31bc10ca7663833c8fd3d513 should improve a lot of this, or at least make it easier to get back to the correct state.
