### ISSUE TITLE
Can't download any plugins?

### ISSUE THREAD

**Issue by Baron7DS** [Zoinkwiz/quest-helper#1281]
I thought at first it was just the Quest Helper plugin because there is no area on the screen you can click to download that plugin. But its like that for every plugin I encounter. Do I have to become a patron to download plugins? If so that should probably be stated beforehand. The only reason I downloaded runelite was because of the Quest Helper plugin.

**Comment by pajlada** [comment]
This is more of a RuneLite question, than a Quest Helper discord.
You do not need to pay anyone anything to download a plugin from the runelite plugin hub.
You can get support for RuneLite in the RuneLite Discord, which you can find here: https://runelite.net/discord
