### ISSUE TITLE
Future Quest?

### ISSUE THREAD

**Issue by Vaulttecs** [Zoinkwiz/quest-helper#129]
First of all, I wanted to say that this plugin has helped temendously and I can only imagine the work that goes into some. So far everything has been seemless. I did want to ask if there were any future plans for quest like exiles or Song of the elves.  Doing Song of the elves with your plugin would make life so much easier. Thank you for your time!

**Comment by Zoinkwiz** [comment]
Hey, the plan is to add all quests eventually. As it happens, I've just finished with SOTE now with https://github.com/Zoinkwiz/quest-helper/commit/bd2273f2ac4a99e910d49554e932e95b69b031fe, so that'll be released in the next release (next few days or so).

**Comment by Vaulttecs** [comment]
Holy shit, that’s awesome. Well I’ve started to use your plugin over slayermusiqs guides haha. Keep it up!
