### ISSUE TITLE
Quest helper not showing on sidebar? 

### ISSUE THREAD

**Issue by Yewsmoke** [Zoinkwiz/quest-helper#1295]
Please help, I recently downloaded questhelper on runelite and now the icon is gone and not showing on my taskbar. The plug in downloaded. I’ve tried removing plug and redownloading and still does not show on taskbar?

**Comment by Felanbird** [comment]
![image](https://github.com/Zoinkwiz/quest-helper/assets/41973452/4d79e21f-6b98-4edd-a29f-de61d9ef7cb1)

Make sure the plugin is enabled

**Comment by Yewsmoke** [comment]
only quest list shows in the search bar..
i dont see quest helper at all when i search.

**Comment by Yewsmoke** [comment]
triple checked to make sure quest helper was installed in my plug-ins

**Comment by Felanbird** [comment]
To re-iterate, `Quest Helper` in the 🔌 tab shows up like this?
![image](https://github.com/Zoinkwiz/quest-helper/assets/41973452/25a117e2-fed3-41fe-bf04-86c18a40223b)

But when you search the 🔧 tab, it shows up like this?
![image](https://github.com/Zoinkwiz/quest-helper/assets/41973452/7bb7a960-124c-4f7d-868b-b4d4fcc573c9)

**Comment by Yewsmoke** [comment]
yes exactly

**Comment by Felanbird** [comment]
Can you join the Runelite discord, whatever is causing your problem it's not Quest Helper related.

https://runelite.net/discord

or click the in-client button found here:
![image](https://github.com/Zoinkwiz/quest-helper/assets/41973452/6d220c31-738d-4019-94b9-9359ea321d9b)

**Comment by Yewsmoke** [comment]
sure no problem, thanks for the replies.
