### ISSUE TITLE
The Giant Dwarf - Missing step

### ISSUE THREAD

**Issue by Sebewe** [Zoinkwiz/quest-helper#1296]
While completing the `Clothes fit for a king` step, it does not correctly guide the player to go to the library speak to the librarian + climb the bookshelf. Had to consult wiki to continue the quest.

**Comment by TsterT** [comment]
The steps are there in the plugin, it just seems to skip over them.
![image](https://github.com/Zoinkwiz/quest-helper/assets/2983021/d3db212e-4b33-483a-8a6b-3702ae4fbc60)

**Comment by Zoinkwiz** [comment]
So from what I can tell, the requirement for the 'Use your coal..' step to be active is:

```java
askedToStartMachine = new Conditions(true, LogicType.OR, 
	new DialogRequirement(client.getLocalPlayer().getName(), 
		"Don't worry, I'll get them for you. Let's see... some coal and some logs. Shouldn't be too hard."), 
	new DialogRequirement("Well, like I said, I can't do anything really without my spinning machine."), 
	new WidgetTextRequirement(119, 3, true, "<col=000080>I must get <col=800000>coal<col=000080> and <col=800000>logs<col=000080>.")
);
```

As it's the requirement in :

```java
getExquisiteClothes.addStep(askedToStartMachine, useCoalOnMachine);
```

Looking at the transcripts in https://oldschool.runescape.wiki/w/Transcript:The_Giant_Dwarf, I don't 'think' any of those should be passing conditions at the pre-book stage, but if it's skipping one must be. If anyone happens to be aware of what might be passing there it'd be much appreciated!

**Comment by Daniel-HarrisNL** [comment]
Odd, I had the quest and attempted to replicate the skipping issue but the steps worked as intended for me. I recorded it just in case it didn't work to review the steps, but got a clip of it working instead. https://www.youtube.com/watch?v=eQsp0Er7z-I
