### ISSUE TITLE
Blue Arrow missing from World Map

### ISSUE THREAD

**Issue by ChasePrince** [Zoinkwiz/quest-helper#1306]
The blue arrow that appears on the World Map once a quest has been selected sporadically works. Most of the time it doesn't. If I close and re-open runelite, it will appear, but only for a very short while.

**Comment by Zoinkwiz** [comment]
This should hopefully have been resolved with https://github.com/Zoinkwiz/quest-helper/commit/460de2970bf3376136c15b3039b4f80557fa4a74.
