### ISSUE TITLE
Ghosts Ahoy missing requirements

### ISSUE THREAD

**Issue by pajlada** [Zoinkwiz/quest-helper#1309]
It looks like completion of The Restless Ghost is required, wiki says otherwise but this post in the Discord shows it's required.

In-game quest requirements: ![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/0eddc8a5-335e-4252-9629-86ff204dbce1)

Their The Restless Ghost quest state: 
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/0ac6be03-9a25-423a-8970-eed76eb72127)

Message when they try to talk to Velorina: 
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/ca4be744-4310-48a7-aaef-ec3fad3d3296)

Originally reported by Volt in Discord https://discord.com/channels/772056816242130964/1162377965200478249

**Comment by cdfisher** [comment]
We were incorrect on the wiki, completion of The Restless Ghost is (now?) required. The appropriate wiki page has been updated.
