### ISSUE TITLE
Misspelling in  Creature of Fenkenstrain

### ISSUE THREAD

**Issue by Xalthox** [Zoinkwiz/quest-helper#1334]
Under the Item Requirements section, The items named," Threads" is misspelled. The correct item is spelled," Thread"

**Comment by lnxd** [comment]
This appears to be consistent with the wording in the specific quest, however not all quests follow this format, for example [Spirits of the Elid](https://oldschool.runescape.wiki/w/Spirits_of_the_Elid)(https://github.com/Zoinkwiz/quest-helper/blob/0aa7b6ac4bb63abdd3399419b657b67cbd5d4972/src/main/java/com/questhelper/helpers/quests/spiritsoftheelid/SpiritsOfTheElid.java#L148)
