### ISSUE TITLE
Hazeel Cult - Kill Alomone step (typo)

### ISSUE THREAD

**Issue by zahti** [Zoinkwiz/quest-helper#1342]
Typo in the step for killing Alomone NPC. https://oldschool.runescape.wiki/w/Alomone

Old (typo): "Kill Almone."
New: "Kill Alomone."

![image](https://github.com/Zoinkwiz/quest-helper/assets/38710634/c799bb32-003d-4f26-a696-17eaef8ab139)

Also, not sure if relevant, but the 'kill' step was skipped over and went straight to looting the chest in the quest helper. Not a big deal, but figured I would mention it.

**Comment by pajlada** [comment]
Typos will be fixed in #1344 
For the skipping of the step, the "Kill Alomone" step is skipped if the NPC can't be found - I suspect the NPC ID we use might be wrong.

Did you do the quest on Leagues or in the main game?

**Comment by zahti** [comment]
@pajlada this was main game! Was leveling up a new hardcore Ironman account yesterday.

**Comment by pajlada** [comment]
Thank you @zahti - I created a new issue for the step being skipped part here: #1350
