### ISSUE TITLE
Mage Arena II Locator helper says MA2 is required instead of MA1

### ISSUE THREAD

**Issue by Intecpsp** [Zoinkwiz/quest-helper#1354]
Title.

To see and use this helper, you have to filter by "Show All". This requirement should be changed to Mage Arena I so that it will filter under "Show Meets Reqs".

**Comment by Intecpsp** [comment]
I assume the fix is a single-character removal from here?

https://github.com/Zoinkwiz/quest-helper/blob/39f3e223dce5f9803e4a5918efdfbf38cb061e5e/src/main/java/com/questhelper/helpers/miniquests/themagearenaii/MA2Locator.java#L144C66-L144C66

**Comment by pajlada** [comment]
> I assume the fix is a single-character removal from here?
> 
> https://github.com/Zoinkwiz/quest-helper/blob/39f3e223dce5f9803e4a5918efdfbf38cb061e5e/src/main/java/com/questhelper/helpers/miniquests/themagearenaii/MA2Locator.java#L144C66-L144C66

Yep! Just gotta change that to mage arena I's enum

**Comment by pajlada** [comment]
I guess it depends a bit what the **Mage Arena II Locator** is for.
**Mage Arena I** is for getting your first god cape.
**Mage Arena II** is for imbuing your god cape, so it guides you to start the miniquest & kill all 3 bosses.
Maybe **Mage Arena II Locator** is for after you've imbued your first god cape during the **Mage Arena II** quest, allowing you to imbue one of your other capes?

**Comment by Intecpsp** [comment]
Potentially, but I've been using it to help complete MA2 the first time.

If it's updated to MA1 as the requirement it helps complete MA2 and any other capes past that.

**Comment by Zoinkwiz** [comment]
So yes the general helper is intended for post-miniquest obtaining of the capes. I put MA2 as the prerequisite as that means this helper should be hidden when filtering by matching reqs until you do the first cape, which'd correctly guide you for going after each boss. If there's a good reason to change it to be just MA1 I'm happy to adjust, but I think in terms of intention it should be okay as is.
