### ISSUE TITLE
Wrong item in Legends' Quest

### ISSUE THREAD

**Issue by eric56379** [Zoinkwiz/quest-helper#1380]
Inside of the section that's titled "Freeing Ungadulu", the quest guide states to use a machete on the tall reeds. However, OSRS requires that you use a knife instead. This occurs once again a couple steps down.

**Comment by Felanbird** [comment]
There's a previous wiki change where a user wanted to change the wording on the grounds that:
`you need to use the machete on the reed, just clicking on it will give you a prompt that tells you to use a knife` (but the wiki already says to use the machete)

Is this the reason why you believe it wanted you to use a knife?

**Comment by eric56379** [comment]
Interesting. I am looking at wikis, and everywhere is stating to use the machete. I already finished the quest, so I can't go back to re-create the issue. You can probably just close the issue and wait to see if someone else runs into what happened to me.

**Comment by Zoinkwiz** [comment]
Closing for now as I think using a machete does work and that it's highlighted for usage during the quest.
