### ISSUE TITLE
Between a Rock, wrong amount of ammo moulds in item requirements

### ISSUE THREAD

**Issue by deafmute1** [Zoinkwiz/quest-helper#1389]
![image](https://github.com/Zoinkwiz/quest-helper/assets/32427188/ce76722a-8615-43af-b7c1-d752238d6353)
Should be 1x.
Issue is repeated in step requirements

**Comment by pajlada** [comment]
Will be fixed by https://github.com/Zoinkwiz/quest-helper/pull/1390 - thank you for the report!
