### ISSUE TITLE
quest helper missing?

### ISSUE THREAD

**Issue by 1sn2s** [Zoinkwiz/quest-helper#1407]
hi there, 

currently trying to do DT2 and my quest helper is missing and try everything to get it back eg re downloading runelite removing quest helper and re intalling, is they another way round this?

**Comment by pajlada** [comment]
These are the steps as described in the Discord, let us know if they help:
> If helper doesn't appear on sidebar or in menu of plugins after installing there are some common things you can try:
> Head to %userprofile%.runelite\plugins and delete the quest-helper jar, then restart client.
> If 1st option did not work, try to delete the cache folder from .runelite and then repeat above step again.

**Comment by Zoinkwiz** [comment]
Hi @1sn2s did the above recommendations work for you?

**Comment by 1sn2s** [comment]
Hi there! Yes it worked a dream thank you very much.

👍🏼

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
