### ISSUE TITLE
Suggestion: Quest/Achievement Diary Export

### ISSUE THREAD

**Issue by Vokuar** [Zoinkwiz/quest-helper#1442]
a quest export for completed quests and/or achievement diaries might be useful when trying to catch a new account up to your current one
so having a export so i don't need to continually log in to the more progressed account would be useful

**Comment by Zoinkwiz** [comment]
Hi there, what aspect of a quest would you want exported, and for what purpose?

**Comment by Vokuar** [comment]
Completed quests so that I can view them in a notepad without having to open the in-game account I can already progress skills as they are all in one screen but if I want to catch up new account to any account that I have had previously I need to make multiple screenshots of the quests I have completed it doesn't matter what format the completed quests are as long as they are readable I could even be in Quest ID numbers as long as I know what Quest name refers to what Quest ID

**Comment by Vokuar** [comment]
So basically completed in progress or stuff like that bit my use case only need completed so ik what to complete on a new account im trying to catch up

**Comment by pajlada** [comment]
If you use the WikiSync plugin, you can put in your username here https://oldschool.runescape.wiki/w/RuneScape:WikiSync/Tracker and see a list of completed quests

**Comment by Vokuar** [comment]
can i output this to text 
like
[completed] a tale of 2 cats
[notcompleted] shield of arrav

so i can sort completed first by searching if it has been completed

**Comment by Vokuar** [comment]
> If you use the [WikiSync plugin](https://oldschool.runescape.wiki/w/RuneScape:WikiSync), you can put in your username here https://oldschool.runescape.wiki/w/RuneScape:WikiSync/Tracker and see a list of completed quests

because this lists in alphabetical order

**Comment by pajlada** [comment]
You could open https://sync.runescape.wiki/runelite/player/pajdank/STANDARD and sort it however you want, replacing `pajdank` with your OSRS username

**Comment by Vokuar** [comment]
this will work lovely thank you

**Comment by Vokuar** [comment]
this works perfectly
