### ISSUE TITLE
Suggestion: Quest Replayability

### ISSUE THREAD

**Issue by Vokuar** [Zoinkwiz/quest-helper#1443]
since player made quests such as cooks helper has shown us client side quests are possible could we replay entire quests using this approach sometimes we want to re-experience a story

**Comment by pajlada** [comment]
This is not something we can pursue - Jagex made a statement essentially prohibiting client side content like that.

**Comment by Zoinkwiz** [comment]
At present there's a pause on any custom content until Jagex comes out with a proper statement on limitations and such. Closing for now, but this could maybe be considered in the future.
