### ISSUE TITLE
Hazeel Cult quest issue

### ISSUE THREAD

**Issue by Evilchiken80** [Zoinkwiz/quest-helper#1466]
During the quest I picked the option to side with Ceril, but the plug in instead showed me the options for the Hazeel choice and I could not change it, in terms of the blue glowing helpers, but I could manually read the instructions for the Ceril option. 

The options said to search the kitchen basement for a key, where as the correct option is to search the cupoboard upstairs in order to prove the butlers guilt.

Lastly, there was no mention of searching the chest a second time to get your own armour piece which I now can't get :(

**Comment by Zoinkwiz** [comment]
Hi @Evilchiken80 , at what point did the plugin shift over to the Hazeel side, straight away after choosing sides with Ceril with Almone? Also, did you do anything different to what the helper suggested prior to the conversation, such as maybe talking to other NPCs?

**Comment by Evilchiken80** [comment]
The Hazeel pathway was chosen by the plug-in straight after I spoke to the NPC and chose the option something along the lines of "no, I wont help you!" which made him jump on the raft which should be the exact option to choose to pick the Ceril side? (sorry I have a terrible memory and could very well have done something wrong, but I do think I followed the guide correctly).

It's all good though, Im loving the plugin and not trying to be a Karen lol , just wanted to raise incase it was a defect or something

**Comment by Zoinkwiz** [comment]
Thanks @Evilchiken80 , my theory is that you might have had a 'poison' item in your bank, if you have a chance would you mind checking if that was the case?

And please don't worry about submitting bug reports, it helps me ensure the plugin is as good as it can be for everyone!
