### ISSUE TITLE
Defender of Varrock: 447 must be + equal [12610, 12611, 12754]

### ISSUE THREAD

**Issue by Frosty-J** [Zoinkwiz/quest-helper#1483]
Does this mean anything? This appears during the second time of collecting 3 mists and the cryptic message goes away once three have been collected.

![screenshot](https://github.com/Zoinkwiz/quest-helper/assets/60154347/0a52f26d-8f9a-4c69-87a1-585749bffa44)

**Comment by Zoinkwiz** [comment]
Thanks for sharing, that's a dev message that shouldn't be appearing! Will be fixed with #1481.
