### ISSUE TITLE
Is Defender Of Varrock supposed to be at the top of the optimal quest ordering?

### ISSUE THREAD

**Issue by AlexGama97** [Zoinkwiz/quest-helper#1494]
It's before many of it's requirement quests and has *relatively* high stat requirements for the others it says should come after (Sheep herder, client of kourend, clock tower, etc)

I assume it just hasn't been ordered properly yet since it came out recently?

**Comment by Zoinkwiz** [comment]
Thanks, this should now be fixed in https://github.com/Zoinkwiz/quest-helper/commit/2fe626a864e325fd9184116298be392e87a31894.
