### ISSUE TITLE
Quest Speedrunning - Resetting Sections/Tasks

### ISSUE THREAD

**Issue by ThienHChu** [Zoinkwiz/quest-helper#1498]
Been doing quest speedrunning for a while on different accounts

I have an issue that kind of slows down my completion of it - I use the quest helper to help me know when to click away from dialogue.

The issue involves abandoning and resetting a run - this often does NOT reset the quest helper and so when I start quest helper back up, it marks a section as complete even though I'm restarting the quest so the section IS NOT complete. The issue here is that I CANNOT click the check mark to say that the section is NOT complete so it continues to identify a section as being done which makes it so that it thinks I'm on a part of a quest I'm not at yet, and won't highlight where I need to go.

**Comment by pajlada** [comment]
I believe this has already been fixed by https://github.com/Zoinkwiz/quest-helper/pull/1447 and will be available in the next release
