### ISSUE TITLE
[Feature Request] Put list of supported quests in the panel when a quest is not active.

### ISSUE THREAD

**Issue by chrstfer** [Zoinkwiz/quest-helper#15]
It would be pretty convenient if there was a list of currently supported quests in the panel when a quest isn't active.

**Comment by Zoinkwiz** [comment]
This should be added now in the live version of the quest helper with https://github.com/Zoinkwiz/quest-helper/commit/4454ecd8fbacdc527d1ef7aa0b29a219b419af26, with the ability to also select and close helpers from the side panel.
