### ISSUE TITLE
Add the ability to hide the "use item" highlight on top of objects

### ISSUE THREAD

**Issue by pajlada** [Zoinkwiz/quest-helper#1502]
From Discord https://discord.com/channels/772056816242130964/776427467560321034/1219394126605320242

The feedback is that this icon 
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/4e117da4-2733-4229-8be6-f4af4c157470)
can be distracting when the object you need to click is small

**Comment by Kolb1jc** [comment]
I 2nd this, it can be annoying when you can't see what is behind the icon
![Screenshot 2024-06-15 145231](https://github.com/Zoinkwiz/quest-helper/assets/172933855/077c31de-ad8e-4f40-b616-239f660f8acf)
