### ISSUE TITLE
How doesnt a HD4000 intergated support thi?

### ISSUE THREAD

**Issue by cleggorz** [Zoinkwiz/quest-helper#1516]
errrr how thf doesn't this plugin work on integrated graphics. I was playing HD RS back when it was launched WAYYYY back in the day. It should work on the most basic integrated gpu. Coming back to the game after nearly 20 years later and my i7 hd 4000 gpu should destroy this. Respectfully. Sometimes a brother wants to use a laptop rather than a dedicated GPU.

**Comment by pajlada** [comment]
This is not the right repository for this report @cleggorz - this repository hosts the Quest Helper plugin.

**Comment by cleggorz** [comment]
> This is not the right repository for this report @cleggorz - this repository hosts the Quest Helper plugin.

Im an alcohol infused dick. I apologise.
