### ISSUE TITLE
At First Light - Quest requirement

### ISSUE THREAD

**Issue by DeSypha** [Zoinkwiz/quest-helper#1530]
Not a huge issue but thought I'd mention it, At First Light requires the completion of Eagle's Peak to be started but isn't shown in Quest Helper under the General requirements. Unless there's a way of getting around it I'm unaware of, linked the wiki for reference:

https://oldschool.runescape.wiki/w/At_First_Light

**Comment by mahabal** [comment]
#1518  - My change was merged in two days ago, not sure when it actually makes it into the client.

**Comment by DeSypha** [comment]
Ah thanks, I tried searching for it first but clearly failed to do so properly. Can close this :)
