### ISSUE TITLE
Kourend Medium Diary Broken?

### ISSUE THREAD

**Issue by itsLucinder** [Zoinkwiz/quest-helper#1534]
Whenever opening Kourend Medium diary, it causes the entire runelite bar to flash and become mostly unusable. Trying to exit out of it doesn't work. Only fix seems to be trying to open a different quest/diary and succeeding

**Comment by pajlada** [comment]
This will be fixed in the next release.
For now, you can disable the "Show full quest requirements" option (make sure it's unticked)
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/3644e537-2360-49cf-b600-ad59436c04ef)

**Comment by Zoinkwiz** [comment]
Fixed with https://github.com/Zoinkwiz/quest-helper/pull/1543.
