### ISSUE TITLE
quest helper not syncing quests

### ISSUE THREAD

**Issue by allengrnwood** [Zoinkwiz/quest-helper#1540]
The quest helper is only showing a select few quests and mini quests. Until I start a quest then it will show me the current quest I'm doing.

**Comment by pajlada** [comment]
Could you check if you have a filter enabled?

**Comment by Zoinkwiz** [comment]
I'm assuming it was a hidden filter issue, so if so hopefully https://github.com/Zoinkwiz/quest-helper/commit/e06c4e9e6b5535e662dc59419b824e18f56d1636 will resolve this. If it's an ongoing issue please let us know.
