### ISSUE TITLE
License are bsd2 but also say all rights reserved?

### ISSUE THREAD

**Issue by adamk33n3r** [Zoinkwiz/quest-helper#1544]
I'm looking to use some of the code from this plugin related to bank filtering and I originally saw that it was licensed as BSD2 so as long as I licensed it the same in my project I'd be good. But upon closer inspection, I noticed that the text also says "All rights reserved" which seems contradictory. Can you explain what this means?

**Comment by pajlada** [comment]
I am not a lawyer, but I think this is a misuse of the license name or the license text (I suspect the latter) - this is the case for the runelite repo as well

**Comment by adamk33n3r** [comment]
I hope the latter as well, I just want to make sure I have permission!

**Comment by adamk33n3r** [comment]
Actually, I just checked my own repo https://github.com/adamk33n3r/runelite-watchdog/blob/master/License and I have the same thing. And I'm pretty sure I used the license template picker on github. So I wonder if github was just being dumb for a while cause it doesn't seem to do that now.

**Comment by Zoinkwiz** [comment]
Hey, yeah I'd just gone with the default license as used by Runelite (as I'd assumed it'd make it the most likely to not cause any issues with it being used as a plugin). I'm happy for you to use my bank filtering code.

**Comment by adamk33n3r** [comment]
Awesome, thank you for the reply!
