### ISSUE TITLE
Minor bug - Draynor Village

### ISSUE THREAD

**Issue by ScullyB96** [Zoinkwiz/quest-helper#1550]
Not really a bug, but having a charged glory does not trigger the green text as it relates to a Draynor teleport.

**Comment by Zoinkwiz** [comment]
Hi @ScullyB96 , for which quest did you have this issue?

**Comment by SpencerSKane** [comment]
#1551 

I searched the quests and was able to find two that could use updates in regards to the Draynor tele. This potentially fixes the issue but can't be certain as we don't know the quest this was encountered on.
