### ISSUE TITLE
Quest Helper not showing several achievement diaries and not showing desert treasure II

### ISSUE THREAD

**Issue by Baronjoe8** [Zoinkwiz/quest-helper#1596]
Hello there, 

My Quest helper has recently stopped showing a few achievement diaries on the drop down list that I haven't completed yet along with Desert Treasure II which I have also not completed and is my last quest to finish (pre While Guthix Sleeps release). I had previously had them on my quest helper through runelite but they have suddenly disappeared and I have no idea why. 

I have most likely pressed something to get rid of it but I have no idea how to get it back, and whilst doing the achievement diaries is no biggie, I would much prefer to use the quest helper tool rather than stop-start on a slayermusiq video if I can avoid it. 

Many thanks,
Baronjoe8

**Comment by pajlada** [comment]
Could you share what your:
 - Filters
 - Difficulty
 - Ordering
 - Skill Filtering


are set to?

**Comment by Baronjoe8** [comment]
I have no words for my idiocy.... That has sorted the problem! I can;t believe I couldn't see the arrow for skill filtering. Sorry for bothering and thank you for the immediate response. LEGEND 💯

**Comment by pajlada** [comment]
No worries, glad it helped!

**Comment by Baronjoe8** [comment]
I had a slayer requirement filter applied 🤦
