### ISSUE TITLE
Incompatible after latest game update

### ISSUE THREAD

**Issue by midlifecriz69** [Zoinkwiz/quest-helper#1607]
![image](https://github.com/Zoinkwiz/quest-helper/assets/173906214/ab6591d9-10eb-4d59-ada5-cfbefda23167)

**Comment by frostiesnow** [comment]
following. same issue and in mid of ds2 :P

**Comment by midlifecriz69** [comment]
Thanks for the quick fix! Working fine now.

**Comment by frostiesnow** [comment]
perfect all fixed, nos all you need to create is it autoclicking the quest for us :)
