### ISSUE TITLE
Crash Due to renderMinimapArrow function

### ISSUE THREAD

**Issue by Jacob-Koger** [Zoinkwiz/quest-helper#1613]
Whenever entering a new location with a quest selected I get a complete game closure, might be due to running with bolt launcher but i have attached the jvm dump as it might assist you
[jvm_crash_pid_64069_r.log](https://github.com/user-attachments/files/16006360/jvm_crash_pid_64069_r.log)

**Comment by pajlada** [comment]
This is a problem with Java 22, if you downgrade to Java 21 it should no longer crash
