### ISSUE TITLE
Highlighting items while not on a quest

### ISSUE THREAD

**Issue by 3-b-c** [Zoinkwiz/quest-helper#1614]
Whether I am on a quest or not, the plugin will highlight bones everywhere. Does not fix with removal and reinstall.
![2024-06-27_00-05-29](https://github.com/Zoinkwiz/quest-helper/assets/44496604/e3389f71-6e5c-4f1a-8593-45555438b94f)

**Comment by 3-b-c** [comment]
![Screenshot from 2024-06-28 14-57-31](https://github.com/Zoinkwiz/quest-helper/assets/44496604/b7115098-3da9-4bf3-bd21-5e4ff0dd5018)
It randomly happens with other items as well.

**Comment by 3-b-c** [comment]
> Try disabling the "highlight all items" option

That did prevent the issue from persisting. But I would still like the feature function. Oh well for now.

**Comment by pajlada** [comment]
Which part of the functionality do you still want?

In case it wasn't clear, even with this disabled, if you start a quest guide, items for that quest will be highlighted. Some changes are being made to clarify this in the next release

**Comment by 3-b-c** [comment]
> Which part of the functionality do you still want?
> 
> In case it wasn't clear, even with this disabled, if you start a quest guide, items for that quest will be highlighted. Some changes are being made to clarify this in the next release

I just wanted the highlighted items while on a quest. All is well. Thank you for the reply.

**Comment by Johndavis2021** [comment]
> Which part of the functionality do you still want?
> 
> In case it wasn't clear, even with this disabled, if you start a quest guide, items for that quest will be highlighted. Some changes are being made to clarify this in the next release

So this is intentional? With "Always highlight needed items" unticked there is 0 markers on the ground, even for the active quest.

Seems a bit annoying you have to turn off the plugin or turn off that setting which you are not questing if you still want items to be highlighted on the floor.

**Comment by Felanbird** [comment]
> So this is intentional? With "Always highlight needed items" unticked there is 0 markers on the ground, even for the active quest.

That is not true, I did `Defender of Varrock` yesterday and the ground items were correctly highlighted while I had `Always highlight needed items` disabled

You probably have another hub plugin breaking quest helper highlighting
