### ISSUE TITLE
Desert Treasure II - Wrong spell highlighted in totem room

### ISSUE THREAD

**Issue by rdhambrick-dev** [Zoinkwiz/quest-helper#1623]
In the room where you must cast a different ancient spell on each of four totems, the wrong spell is highlighted in the spellbook:

1. ? was highlighted for the Blood Totem (I don't remember which, I just noticed that it was incorrect)
2. ? was highlighted for the Shadow Totem
3. Blood barrage was highlighted for the Smoke Totem 
4. Nothing was highlighted for the Ice Totem

![2024-07-04_11-53-55](https://github.com/Zoinkwiz/quest-helper/assets/114700634/27c1dd58-6322-4d3f-abea-2d9a55b30b95)

**Comment by FounderCasey** [comment]
Just bumping as this is still an issue
