### ISSUE TITLE
While Guthix Sleeps broken

### ISSUE THREAD

**Issue by Yidz** [Zoinkwiz/quest-helper#1636]
I have not started the quest, I right click it and press start quest helper but it just changes my side tab to the quest helper plugin and i can see that while guthix sleeps is available but even clicking the arrow next to it does nothing

**Comment by KBoumghar** [comment]
@Yidz It hasn't been added / coded yet, only a placeholder was added.

**Comment by pajlada** [comment]
This should now work as expected with 4.7.7.1
