### ISSUE TITLE
Ratcatcher's Updated Dialog

### ISSUE THREAD

**Issue by coopermor** [Zoinkwiz/quest-helper#1660]
The ratcatcher's dialog was [updated](https://secure.runescape.com/m=news/colosseum-npc-clickboxes--more?oldschool=1). The text helper does not highlight this dialog. 
![2024-07-26_21-16-48](https://github.com/user-attachments/assets/9bf19777-6a74-4822-a5ea-ea930963e197)

**Comment by maxwelldixon** [comment]
Hi @coopermor, I submitted a PR [#1692](https://github.com/Zoinkwiz/quest-helper/pull/1692) with the updated dialog.
