### ISSUE TITLE
Below Ice Mountain and Black Knight's fortress in Quest Helper

### ISSUE THREAD

**Issue by jwombacker78** [Zoinkwiz/quest-helper#1665]
Below Ice Mountain and Black Knight's Fortress cannot be searched in Quest Helper but can be accessed if viewing a quest that has those as requirements. Clicking "Finished Below Ice Mountain" link will bring me to the correct section but cannot be accessed via the main tab of quest helper

**Comment by kcjg94** [comment]
Do you have the setting on to hide completed quests? 

I was unable to reproduce your issue. 

![image](https://github.com/user-attachments/assets/b9adb75c-9fb2-42a7-91cd-420e04155058)
