### ISSUE TITLE
Plugin does not work with update

### ISSUE THREAD

**Issue by MickyDsTea** [Zoinkwiz/quest-helper#1694]
Plugin doesnt work

**Comment by Zoinkwiz** [comment]
The fix has just been deployed, you can reload your client to see it again.

**Comment by Zoinkwiz** [comment]
You can try uninstalling and re-installing it, let me know if that doesn't work!

**Comment by MickyDsTea** [comment]
Was trying that now! It worked thank you!
________________________________
