### ISSUE TITLE
Add contributing guide / basic development workflow 

### ISSUE THREAD

**Issue by evsl** [Zoinkwiz/quest-helper#17]
I'm sure quite a lot of players (myself included) would love to contribute, but at a glance it seems to be rather difficult to go about testing as you develop. Some steps to get developers started would be very helpful.

For example, say hypothetically someone were wanting to help by implementing a quest. I'll use a rather high level quest such as Monkey Madness II as an example, but this generally applies to every quest; at a glance from an individual external to the project it seems impossible to follow typical iterative development practices, debug and otherwise make meaningful progress in that endeavor without having multiple accounts with the requirements to complete that quest, and running through it multiple times.

A basic workflow or guidelines on how you generally go about implementing new quests would be great!

**Comment by Zoinkwiz** [comment]
Added the basics in https://github.com/Zoinkwiz/quest-helper/wiki/Contribution-guide, I'll hopefully be able to add more details and make it more thorough with time.
