### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by michaelrs69** [Zoinkwiz/quest-helper#170]
i see no blue arrows or guide info popping up anymore. ever since i did a step wrong and didnt take all the map parts in dragon slayer 2. and when i tried to start other quests noting popped up

**Comment by Zoinkwiz** [comment]
Hi @michaelrs69 , could you expand on what's not working (just clicking this helper won't start now? All helpers?), and exactly what step of the quest stopped working. Also, if you do the next step of the quest, is the helper able to be started again?

**Comment by michaelrs69** [comment]
Yes it's working.  I'll I didnt was click the quest log and after
refreshing it
