### ISSUE TITLE
While Guthix Sleeps - Restoration potion ingredients

### ISSUE THREAD

**Issue by PropaneTA** [Zoinkwiz/quest-helper#1708]
The Temple section, Quest helper says that you need snapdragon & red spider's eggs for the restoration potion but you  can also use harralander & red spider's eggs. The druid dropped an harralander for me.

**Comment by Zoinkwiz** [comment]
Should be fixed now with https://github.com/Zoinkwiz/quest-helper/commit/e25088856119160a116f3e7590c73735abc4b35a
