### ISSUE TITLE
While Guthix Sleeps is first on the Optimal list

### ISSUE THREAD

**Issue by minime220220** [Zoinkwiz/quest-helper#1709]
Shouldnt that quest be way at the bottom? It requires 180 qp so it has to be a mistake.

**Comment by Felanbird** [comment]
It looks like this was handled for the Optimal Ironman list but not the Optimal regular list

**Comment by minime220220** [comment]
So I see where you fixed it, but on my end it still shows WGS on top. I have restarted runelite a few times to check again. Do I need to wait for the next RL update?

**Comment by pajlada** [comment]
> So I see where you fixed it, but on my end it still shows WGS on top. I have restarted runelite a few times to check again. Do I need to wait for the next RL update?

You'll need to wait for the latest version of Quest Helper to be merged into RuneLite
