### ISSUE TITLE
A Soul's Bane: Confusion Beast Room

### ISSUE THREAD

**Issue by larsiny** [Zoinkwiz/quest-helper#1710]
The quest helper says to find the correct confusion beast and highlights all of them. The correct confusion beast to attack is always the one with NPC ID 1067.

Fix should be pretty simple: remove this line and update the message above it: https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/helpers/quests/asoulsbane/ASoulsBane.java#L249-L250

**Comment by Zoinkwiz** [comment]
This is intentional, as we don't want to provide information to the player that they'd otherwise be unable to obtain themselves, as adjusted in https://github.com/Zoinkwiz/quest-helper/commit/530d2ee28fd4a6a712e2da8a1bcde2aa8646dccf.
