### ISSUE TITLE
Temple of Ikov: Missing Information

### ISSUE THREAD

**Issue by dlarocque** [Zoinkwiz/quest-helper#173]
There are some minor things that could be added to the Temple of Ikov quest that might be redundant but thought I'd mention anyway.
- Tell player to put on Pendant of Lucien before 'Cross the bridge in the north room and pick up the lever whilst weighing less than 0kg', as players need to be wearing the pendant to enter the northern room
- Give warning about level 61 aggressive spiders and level 82 aggressive demons
- Could mention that players must defeat the 'Fire Warrior of Lesarkus (level 84)' with ranged at the start of the quest (and recommend gear accordingly)
- If siding with Lucien during the quest, the player will have to kill a 'Guardian of Armadyl (level 43)' before stealing the 'Staff of Armadyl' on the table.

**Comment by dlarocque** [comment]
I'd be interested in adding the info myself since it's so minor

**Comment by Zoinkwiz** [comment]
Added in 7a62d7d05ab27b0e7e7d228a962cb1db60cf995f.
