### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by iDznPB** [Zoinkwiz/quest-helper#175]
Not sure if it's just me, but I have to keep clearing and re-adding monkey madness 1 in order for the plugin to update.

**Comment by Zoinkwiz** [comment]
Are you on Runelite or another client @iDznPB ? This has been a known issue for other clients, but not from our side.

**Comment by iDznPB** [comment]
Ah that might be my fault then, I was using it on OPRS, I wasn't aware there would be a difference, I'll jump back to RL. Thanks for getting back to me!
