### ISSUE TITLE
Legends' Quest performance

### ISSUE THREAD

**Issue by rekterakathom** [Zoinkwiz/quest-helper#185]
My FPS dropped to around 20 during the segment in which you have to obtain crystal shards from the skeletons. Back to 50 after I formed the heart.

Found this spammed in my logs, I am not certain if this relates to the issue.
https://pastebin.com/Sj352B24

**Comment by Zoinkwiz** [comment]
Should hopefully be fixed now, if anyone else encounters this issue I'm happy to re-open and investigate further.
