### ISSUE TITLE
Wrong legs in requirements of sote

### ISSUE THREAD

**Issue by Jellearends** [Zoinkwiz/quest-helper#203]
In Sote 2nd part it needs to be steel legs instead of ardougne knight platelegs
![image](https://user-images.githubusercontent.com/46443665/107379122-e9118e00-6aec-11eb-9376-83bc9297e43a.png)

**Comment by Zoinkwiz** [comment]
Thanks, fixed with https://github.com/Zoinkwiz/quest-helper/commit/054383c21cf2c6b02a01add2fcc7c7f03d950de1.
