### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by og-seph** [Zoinkwiz/quest-helper#21]
Cheers, Idk if it's from you're side or Runelite but it doesn't seem to auto update or neither update at all, The latest update inside of runelite is 1.1.1 but it doesn't seem to be the latest one according to ur ghub.

Regards

**Comment by Zoinkwiz** [comment]
Hi @og-seph , I need to make a pull request to the plugin hub (https://github.com/runelite/plugin-hub), so the core Runelite team can review it. I'm planning on making a PR tonight prior to the leagues starting tomorrow, so hopefully any changes up to now will be available soonish.

**Comment by Zoinkwiz** [comment]
As an update, a PR is now up in https://github.com/runelite/plugin-hub/pull/713. Once that's merged in the changes should appear in the plugin hub.
