### ISSUE TITLE
Bug at Royal Trouble, Digging Deeper step

### ISSUE THREAD

**Issue by tobiasstier** [Zoinkwiz/quest-helper#23]
After talking to Mathilda, it will say to speak to Advisor Ghrim, and continually point to the stairs to the throne room in Miscellania Castle, though you will have to speak to Vargas first.
<img width="727" alt="Screenshot 2020-10-28 at 09 50 58" src="https://user-images.githubusercontent.com/17247387/97413445-156d1a00-1903-11eb-98a9-edf726be734f.png">

**Comment by Zoinkwiz** [comment]
The linked commit should fix this, thanks a lot for raising the issue and the details, they helped make it a quick fix 😃
