### ISSUE TITLE
Fremennik Isles

### ISSUE THREAD

**Issue by xSlysoft** [Zoinkwiz/quest-helper#236]
Small issue I just found with Fremennik Isles, after beginning the quest the helper does not update from "Travel to Jatizso with Mord" until you walk to Jatizso and open the main gate. I'm not sure if this is intentional or not.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/912b480cef2e85bbad4f06acceff248385ef451a, thanks for raising.
