### ISSUE TITLE
Royal Trouble target markers

### ISSUE THREAD

**Issue by gergely-kovacs** [Zoinkwiz/quest-helper#24]
Hi!

I'm doing the quest right now, and I noticed the target marker for the sailor is pointing to an inaccessible island, instead of the docks.
Also, there's no marker for the queen and the king between talking to Matilda and the advisor.
I'm using Quest Helper 1.1.1 with RuneLite 1.6.29 (on win 10 64 bit if that matters).

Thanks a lot for your work!

![sailor-marker](https://user-images.githubusercontent.com/13271589/97450667-42d1bc00-1933-11eb-902e-c4ea61a37d03.png)

**Comment by gergely-kovacs** [comment]
Also, if you read the _Burnt diary_ before adding all the pages, the remaining fires won't be marked, and the crevice is targeted instead.

**Comment by Zoinkwiz** [comment]
Hi, these issues should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/2e396b666d16aa00156bc28a362f5d20fcd411ae. Thanks for reporting them!
