### ISSUE TITLE
Plugin causing new chunks/instances to freeze

### ISSUE THREAD

**Issue by james-gould** [Zoinkwiz/quest-helper#247]
After the 6 Jads update quest helper is causing the client to load a new chunk for several seconds.

To repeat:

- TP to a new location
- Try to interact with the game after the chunk has loaded
- Works best for places with NPCs walking around. Fally, lumbridge are good options.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/f3eb5abd135acbb26e0ab40ebfa02f3959b1aef3, reload Runelite for the change to take effect.
