### ISSUE TITLE
Mountain Daughter

### ISSUE THREAD

**Issue by Lukas4RS** [Zoinkwiz/quest-helper#249]
The plugin could be further improved for the Mountain Daughter quest. Suggested improvements:

Part 2: Go to the centre....
1. It currently does not highlight where to pick up 'Mud' and 'Pole' required for the next quest step
Part 7: Tell Hamal about...
1. It repeats the instruction twice
Part 8: Tell Asleif about...
1. It does not highlight the actions (e.g. use pool on rocks) as it did in the previous parts
Part 11: Bury Asleif
1. It does not highlight the actions (e.g. use pool on rocks) as it did in the previous parts

**Comment by Zoinkwiz** [comment]
These should have been applied in https://github.com/Zoinkwiz/quest-helper/commit/929d392226cac80e4600a6bfc27518bec5f5df12.
