### ISSUE TITLE
The Golem quest guide step "talk to Curator Haig Halen" does not work

### ISSUE THREAD

**Issue by DriesWambacq** [Zoinkwiz/quest-helper#25]
When I tried doing The Golem, I got stuck at the abovementioned step. I only got 3 dialogue options and no options related to the quest. I googled what could be the problem and it seems that you need to at least enter the Uzer ruins once before you can get the correct dialogue option from the Curator.

**Comment by Zoinkwiz** [comment]
Hey, thanks for raising, this should hopefully be fixed now with https://github.com/Zoinkwiz/quest-helper/commit/8235492cc89a926e33e8f65a882b3a0d6a636fb9.
