### ISSUE TITLE
Regicide missed step after leaving Underground Pass

### ISSUE THREAD

**Issue by SapiensAnatis** [Zoinkwiz/quest-helper#253]
I was just doing Regicide with the plugin and once I left the Underground Pass it told me to go straight to Iorwerth. He said he was too busy to talk to me -- turns out, you're supposed to wait for an elf to spawn and talk to you and then get killed.

**Comment by Zoinkwiz** [comment]
Added clarification to the step in https://github.com/Zoinkwiz/quest-helper/commit/84b634950e296a477ac03a91a5d538cfd561b7bf.
