### ISSUE TITLE
Ability to disable quest debug window

### ISSUE THREAD

**Issue by emiljensen2** [Zoinkwiz/quest-helper#254]
Title, It seems to be like a debug function that can't be disabled.
Doesn't seem like "var" would makes much sense to any end user, and there's already a window that says quest name.

**Comment by Nightfirecat** [comment]
For what it's worth, I run the client with `--debug` whether I'm on release or a dev build simply to ensure I can review logs for chat and plugin messages down the line if need be. If you're looking to make some other trigger for this overlay, I recommend subscribing to `CommandExecuted` for some `::questhelperdebug` type of rs chat command.

**Comment by Zoinkwiz** [comment]
Removed it and made it work with `questhelperdebug` per @Nightfirecat 's suggestion in f7fae655d810317b4d71e6940f11136eddeb083d, thanks both.
