### ISSUE TITLE
Wanted! wrong step location

### ISSUE THREAD

**Issue by hex-agon** [Zoinkwiz/quest-helper#258]
In the following step, the quest helper highlights the wrong location, instead of pointing to the wilderness it is pointing to draynor manor.
![image](https://user-images.githubusercontent.com/4876366/111088024-ddf2b900-8503-11eb-8113-542cf62ae295.png)

**Comment by Zoinkwiz** [comment]
Fixed in https://github.com/Zoinkwiz/quest-helper/commit/20bcf8e7e36f48100083384a887fb5109c7a0cf0, thanks 😄
