### ISSUE TITLE
Small QoL Request

### ISSUE THREAD

**Issue by D-uncanClark** [Zoinkwiz/quest-helper#26]
Hey, could you add the keybind of the dialogue choice to the overlay widget in a nice bright colour?

https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/steps/choice/DialogChoiceSteps.java 
I think that this is the chat choice place.

https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/panel/QuestStepPanel.java
That may be the panel place, not really sure though.

When an npc has 4 dialogue options to choose from, the correct one (3 for example) would add the default dialogue option keybind (big blue 3 in this case) to the overlay widget in the top left.

Sick plugin, 10/10
Cheers.

**Comment by Zoinkwiz** [comment]
This has been added to the option itself now, so hopefully should make it clear what keybind to press.
