### ISSUE TITLE
Mourning's End Part II - Final pillar warning is saying wrong direction when you're about to leave

### ISSUE THREAD

**Issue by DelVision** [Zoinkwiz/quest-helper#268]
The capitalized text before you're about to leave says to turn the pillar to north, but you're supposed to turn the last pillar back to "east" before leaving.

I just got confused about that part, not like you can turn it anywhere else than west or east or up.. But just wanted to make sure that it's not too confusing for others because it's quite important step to get right.

**Comment by Zoinkwiz** [comment]
Thanks, will be fixed with **https://github.com/Zoinkwiz/quest-helper/commit/a935e4e845bf59d71f11f2a1ae6f6bdd3679c45a
