### ISSUE TITLE
zorge flesh eaters diolog not properly working

### ISSUE THREAD

**Issue by mjkiyoi69** [Zoinkwiz/quest-helper#27]
sorry for the lack of detail but i figure something is better than nothing.
durring the part of the quest after you come back up the stairs after putting the potion in the tea it highlights the first dialog option only and basically loops i had to just click the others and the quest moved forward. loving the plugin tho id probs be hitting a record if i didnt get stoped here gonna grind the whole list

**Comment by Zoinkwiz** [comment]
Should be fixed with the most recent release.
