### ISSUE TITLE
Missing step in The Feud

### ISSUE THREAD

**Issue by Zoinkwiz** [Zoinkwiz/quest-helper#271]
The quest wont update to the find the beef step after giving the guy 3 beers.
it comes back after talking to the 2 gang members.

**Comment by Kerpackie** [comment]
This should(?) be resolved in the rewrite in commit c7c064d , I don't remember running into the issue while testing.

There can sometimes be an issue with VarBit 318 updating when you give him the beers, as it doesn't update until after dialogue has been completed, which could be causing the issue?
