### ISSUE TITLE
Accessibility options for requirements text colors

### ISSUE THREAD

**Issue by nnapolitano** [Zoinkwiz/quest-helper#272]
As a User

I want to have a colorblind option for the missing items/ missing requirements, as red text is hard to read sometimes

Suggested action: 
An accessibility setting to disable the text colors completely would be easiest (making everything white on black or similar high contrast settings).. not as fun, but easy to read. 

Or adding options for custom text colors for requirements would probably work too, may take more effort though than a static color override

**Comment by Zoinkwiz** [comment]
Added with https://github.com/Zoinkwiz/quest-helper/commit/e355c9bc6f602061cf5b6e220914e8a94adbcbf4. Let me know if I've missed anythjing with that.
