### ISSUE TITLE
The Fremennik Exiles Start NPC is incorrect

### ISSUE THREAD

**Issue by Jakezxz1** [Zoinkwiz/quest-helper#276]
I started the quest and the NPC defaulted to Thora the barkeep - The text panel correctly displays Brundt but he is not highlighted, nor is his text option for appropriate quest start.

May have been small bug.

**Comment by Zoinkwiz** [comment]
She is highlighted for 'buy 2 kegs before starting the quest'. I'll include it as a step in the sidebar now with https://github.com/Zoinkwiz/quest-helper/commit/b2e1829acc9c32c18fe44b6b914637c27072c0c6.
