### ISSUE TITLE
The Fremennik Trials

### ISSUE THREAD

**Issue by Streammz** [Zoinkwiz/quest-helper#278]
During my attempt of The Fremennik Trails, I came across a few things that slowed me down in the quest. I listed them here as reference. I am not sure if all of these would be possible to fix, maybe it's things that are impossible to track, but a few things might be helpful. The helper already shows notes warning about de-syncs being fixed by opening the quest journal.

Related helper: [The Fremmenik Trials](https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/quests/thefremenniktrials/TheFremennikTrials.java) Quest Helper

**Olaf's task: Talk to Olaf the Bard north east of the longhall.**
Step is not seen as completed until you open the quest journal.

**Olaf's Task: Use a knife on the branch to make an unstrung lyre**
The step is working fine, but could benefit from some inventory highlighting on the knife and the branch.

**Olaf's Task: Use the golden wool on your unstrung lyre**
The step is working fine, but could benefit from some inventory highlighting on the golden wool and the unstrung lyre.

**Manni's Task: Talk to Manni the Reveller in the Rellekka longhall.**
Step is not seen as completed until you open the quest journal.

**Manni's Task**
Completing the last step of this task, thus earning Manni's vote, does not tick off the completing of Manni's task in the quest helper.

**Sigli's Task: Use the hunter's talisman to hunt down the Draugen.**
The step is working fine, but could benefit from some inventory highlighting on the talisman. Additional note, the helper calls it `hunter's talisman`, but the item is called `Hunters' talisman`; missing both a capitalisation, and the apostrophe being incorrect.

**Sigli's Task**
Completing the last step of this task, thus earning Sigli's vote, does not tick off the completing of Sigli's task in the quest helper.

**Sigmund's Task: Talk to Olaf the Bard east of the longhall.**
I had to talk to Olaf twice for the helper to progress to the next step. I'm not certain, but I believe talking to him once is enough for the quest itself to actually progress.

**Sigmund's Task: Talk to Brundt in the longhall.**
If the quest Mountain Daughter is completed (or maybe also in progress), the chat options consist of the following initially, but neither are hightlighted:
- Ask about the mountain camp.
- Ask about anything else.

The anything else option should be picked in this case.

**Sigmund's Task**
Completing the last step of this task, thus earning Sigmund's vote, does not tick off the completing of Sigmund's task in the quest helper.

**Thorvald's Task: Talk to Thorvald north of the longhall.**
To complete the step, you have to pick a dialog option (I picked yes). Neither yes or no were marked as correct.

**Thorvald's Task**
Completing the last step of this task, thus earning Thorvald's vote, does not tick off the completing of Thorvald's task in the quest helper.

**Peer's Task: Enter the solution to Peer's door.**
Having the combination lock puzzle open reverts back to the previous step, hiding the proper solution for the user.

**Comment by NicholasDreyer** [comment]
I have an additional improvement and confirmation for tasks not completing properly as well.

**Manni's Task**
The step to use the low alcohol keg on the regular keg after putting the strange lit object in the pipe is missing.
I can confirm that the section does not get automatically get marked as completed after beating him in the drinking contest.

**Sigli's Task**
Also confirming that it does not automatically get marked as completed after the final dialogue.

**Sigmund's Task**
Also confirming that it does not automatically get marked as completed after the final dialogue.

**Thorvald's Task**
Also confirming that it does not automatically get marked as completed after the final dialogue.

**Peer's Task: Enter the solution to Peer's door.**
The solution to the puzzle disappears after the puzzle dialogue. I believe it would be more convenient if the solution stays after the dialogue and while the player is inputting the code.

Amazing plugin by the way!
