### ISSUE TITLE
Unable to start quest help if under required stats (even when boostable)

### ISSUE THREAD

**Issue by sxt9** [Zoinkwiz/quest-helper#28]
I'm unable to start the quest help for "Rum Deal" due to my farming requirement being below 40 though I'm able to boost >40 with Brown Spice from Evil Dave's lair.

Thank you.

UPDATE - I now have 40 Farming and am still unable to run the "Rum Deal" quest helper. My apologies for the confusion w/ title.

**Comment by Zoinkwiz** [comment]
Hey, thanks for the report, this should be fixed now with https://github.com/Zoinkwiz/quest-helper/commit/497276bf4365d01e1c36983d2824b289ca1bf124.
