### ISSUE TITLE
Unable to select Rum Deal.

### ISSUE THREAD

**Issue by SagerWilliams** [Zoinkwiz/quest-helper#29]
All other quests get started when clicking the arrow except for Rum Deal. I just completed Zogre Flesh Eaters with a similar problem to another issue (Not proceeding after getting info on how to take care of things. Was able to continue on my own.)

**Comment by Zoinkwiz** [comment]
This should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/497276bf4365d01e1c36983d2824b289ca1bf124, which'll be live in a day or two.
