### ISSUE TITLE
The Lost Tribe - missing step

### ISSUE THREAD

**Issue by kam92** [Zoinkwiz/quest-helper#294]
![image](https://user-images.githubusercontent.com/79944246/115971554-6d39b600-a51f-11eb-94d9-19cd670a0ae4.png)

Where I added a red line, should be added:

Tell the duke that Sigmund is part of Humans Against Monsters.

Otherwise (as is now), player won't be able to enter HAM Lair.

**Comment by Zoinkwiz** [comment]
You can always enter the HAM lair, whether you've done any of this quest or not. Were you trying to pick the lock on the trapdoor?

**Comment by kam92** [comment]
> You can always enter the HAM lair, whether you've done any of this quest or not. Were you trying to pick the lock on the trapdoor?

I was trying to pick the lock, however I read about it and it may be a game bug that you need to hop worlds to fix.  Sorry!
