### ISSUE TITLE
Help with Contributing

### ISSUE THREAD

**Issue by llamositopia** [Zoinkwiz/quest-helper#3]
Hey, I think this plugin is great and would love to contribute. I hope you're open to some open-source contribution.

I'm partway through writing a pull request to include Underground Pass, but some things are a little muddy:
1. Do you normally collect all the necessary info by just stepping through quests with the dev tools on and writing down NPC/object IDs? Is there some quicker way to collect all this info?
2. Do the integer keys in BasicQuestHelper#loadSteps correspond to the VarPlayer state of the quest, or are they arbitrary?
3. What's the difference between using QuestStep#addSubstep and ConditionalSteps?

Thanks for the awesome plugin and info

**Comment by Zoinkwiz** [comment]
Hi, sure I'm very happy for people to help out where possible! Regarding your questions:

1. I have indeed largely just gotten my info going through the quest, with the Var Inspector on, and using the dev tools to check positions/ids/etc. If you come across a more efficient manner of doing things, please do let me know!

2. The keys correspond to the current Varbit or Varplayer for the quest (which depends on how old the quest is basically).

3. addSubStep is used for having multiple steps count as a single 'step' in the sidebar (so you don't need say 20 'click the puzzle tile', just a single master 'step' which represents all of them, and is highlighted in the sidebar when you're doing it). The ConditionalStep is used to choose what step should currently be presented, based on the conditions specified. This is largely necessary for any quest section where its varbit/varp doesn't change but multiple actions are required. For example:

```
// Set up the conditional step. 'enterPass' is made the default step of this, and thus the one selected if all other conditions fail
ConditionalStep goThroughUndergroundPass = new ConditionalStep(this, enterPass);

// You can then add conditions and potential steps to the ConditionalStep. 
// Logically the checks will go from top to bottom, so in this example, 
// even if you have both a cloth (hasCloth passes) and a lit arrow (hasLitArrow passes), 
// as the hasLitArrow line is higher it'll be used.
goThroughUndergroundPass .addStep(new Conditions(hasLitArrow, inFirstRoom), fireArrowAtRope);
goThroughUndergroundPass .addStep(new Conditions(hasClothArrow, inFirstRoom), useArrowOnFire);
goThroughUndergroundPass .addStep(new Conditions(hasCloth, inFirstRoom), addClothToArrow);
goThroughUndergroundPass .addStep(inFirstRoom, getCloth);
```

At some point I need to work on compiling details on all of this in this repo's wiki to help with contributing. Let me know if I can help with anything else.

**Comment by llamositopia** [comment]
Awesome! That clears things up. 

Thanks for the quick response, I'll be back with a PR soon enough :)
