### ISSUE TITLE
Rum Deal quest does nothing when the quest is opened.

### ISSUE THREAD

**Issue by AlexAppleManzer** [Zoinkwiz/quest-helper#30]
Clicking on the Rum Deal quest in the side panel does nothing.

here are my runelite logs on the crash
[client.log](https://github.com/Zoinkwiz/quest-helper/files/5466029/client.log)

**Comment by Zoinkwiz** [comment]
This should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/497276bf4365d01e1c36983d2824b289ca1bf124, which'll be live in a day or two.
