### ISSUE TITLE
Mountain Daughter Quest Overlook

### ISSUE THREAD

**Issue by MsngTxtrs** [Zoinkwiz/quest-helper#301]
Durring the quest, once you get permission to look for the daughter, the quest helper tells you to use mud on the tree, while the highligted action only tells you to go to the tree and doesnt have you pick up mud at any point. Basically what im asking is during the second section add a step to grab mud.

**Comment by Zoinkwiz** [comment]
Could be possible, there's not a way to know if there tree has mud on it so perhaps a locking condition check for if you've ever had mud would do, along with the existing item tip.

**Comment by connor1234562** [comment]
not only does the quest guide not specify that you will need to grab mud, it also doesnt mention grabbing the broken pole before you climb the tree.
