### ISSUE TITLE
Murder Mystery

### ISSUE THREAD

**Issue by allenkinzalow** [Zoinkwiz/quest-helper#303]
After getting flour and using it on the dagger the quest appeared to get "stuck" on that step. I followed the wiki the the following step of using flour on the needle and pot. After that the quest guide was permanently on the following screen (tried opening quest menu, no help):

![download (1)](https://user-images.githubusercontent.com/2922507/116762837-b9866980-a9e9-11eb-96b9-b3680693bf92.png)

The quest helper sidebar was stuck on "Talk to the Guard in the Sinclair Manor north of Camelot.
I followed the osrs wiki for the remainder of the quest.

Side note: It would be helpful if the step before going upstairs to search Elizabeth's barrel was to click the stairs, otherwise the map arrow points to the North East, same for going back downstairs to fill your pot with flour.

**Comment by Ogieeeeee** [comment]
+1
