### ISSUE TITLE
wrong info shown in infobox

### ISSUE THREAD

**Issue by oslokebab** [Zoinkwiz/quest-helper#304]
during in aid of the myreque the infobox shows 10x raw mackerel instead of 10x raw snails.

**Comment by Zoinkwiz** [comment]
Which infobox says that to clarify @oslokebab ?

**Comment by oslokebab** [comment]
what do you mean

**Comment by oslokebab** [comment]
infobox when the guy asks you to fill in the crate with supplies

**Comment by Zoinkwiz** [comment]
What are you referring to as the infobox. The overlay, the sidebar, or something else?
