### ISSUE TITLE
Fremmy Isles ores requirement wrong

### ISSUE THREAD

**Issue by SeanYHe** [Zoinkwiz/quest-helper#31]
https://github.com/Zoinkwiz/quest-helper/blob/b319672fbbf8e48a27e4b8f42bee2bd24673c329/src/main/java/com/questhelper/quests/thefremennikisles/TheFremennikIsles.java#L296-L307

The coal and mithril check should be flipped. Currently it will recommend coal for mining level >= 55 as well.

**Comment by Zoinkwiz** [comment]
Good spot, fixed in https://github.com/Zoinkwiz/quest-helper/commit/e27b0b37d1e150f02b21bbefc0e21b30ea7e061f, thanks!
