### ISSUE TITLE
Monkey Madness II Tunnels not showing the correct path.

### ISSUE THREAD

**Issue by mrwhisker23** [Zoinkwiz/quest-helper#314]
The quest helper plugin directs me to take the path shown in the picture, but the chat says I shouldn't be taking this path. The plugin should update when it sees that this is not the right path.

Side note: Every branch I had to take was opposite the one the helper told me to take, but that may just be my piss luck.

![Runelite_2021-05-07_04-33-08](https://user-images.githubusercontent.com/7873992/117422452-9bd76980-aeed-11eb-9fda-d056ffb3916f.png)

**Comment by ZenithStar** [comment]
I also just experienced this issue. Perhaps it's because my route includes what could be considered backtracking. Pictured below, my route in MSPaint red
![2021-12-11_19-12-53](https://user-images.githubusercontent.com/12200619/145696816-42c03c4b-6592-4e9e-b8db-047943c5bf60.png)
.

**Comment by pystic-mizza** [comment]
Experienced the same issue.

**Comment by icorne** [comment]
Doing the quest now, i'm having the same issue

**Comment by Zoinkwiz** [comment]
This was hopefully resolved in https://github.com/Zoinkwiz/quest-helper/commit/62246f27689e0fb85ad58dcc5810b31608287505 so closing now.
