### ISSUE TITLE
Rum Deal dosn't seem to open/start in the quest helper?

### ISSUE THREAD

**Issue by Bronith** [Zoinkwiz/quest-helper#32]
Runelite plugin version 1.1.2
Rum deal dosn't open when you click the little arrow on the right next to the title. It instead just jumps back up to the search bar, and nothing happens afterwards. This might simply be because the quest isn't supported yet though. So sorry if that is the case. Love your plugin, I am a new player in osrs and I wouldn't have been able to enjoy the game the same way without it. So thank you for your great work.

**Comment by Zoinkwiz** [comment]
Thanks for the report, this should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/497276bf4365d01e1c36983d2824b289ca1bf124 and working correctly with the next version release.
