### ISSUE TITLE
My arm's big adventure missing item

### ISSUE THREAD

**Issue by ADSFikosdahfjkijsdah** [Zoinkwiz/quest-helper#323]
At the part 'prepare to grow' you need to put ugthanki dung on the patch but you need a spade for it, lucklily I had one with the tool leprechaun but it isn't mentioned in the required items list

**Comment by ADSFikosdahfjkijsdah** [comment]
I mean it is actually mentioned in the main item list but not at the particular part

**Comment by Zoinkwiz** [comment]
Should be fixed now, thanks.
