### ISSUE TITLE
Kourend Quests don't show requirement X Marks the Spot

### ISSUE THREAD

**Issue by njhargis** [Zoinkwiz/quest-helper#329]
The Depths of Despair, The Queen of Thieves, Tale of the Righteous,The Forsaken Tower, The Ascent of Arceuus all are missing the requirement of X Marks the Spot

**Comment by aclogar** [comment]
This is exactly how Jagex lists required quests in the quest log and offical pages.  Client of Kourend is the required quest and X Marks the Spot is a requirement for that quest.

**Comment by Zoinkwiz** [comment]
I've added it although it's technically now required for Client of Kourend, to avoid confusion for older accs.
