### ISSUE TITLE
The Lost Tribe incorrectly indicates you only need to talk to Hans

### ISSUE THREAD

**Issue by Zoinkwiz** [Zoinkwiz/quest-helper#33]
I believe the correct NPC you need to talk to is random, so need to either have the player talk to everyone until they get the right one, or find out a way to work out which NPC is correct.

**Comment by MildPanda** [comment]
Having this issue too. Here is a video https://streamable.com/llxtzm

**Comment by MildPanda** [comment]
According to the slayermusiq1's video you need to talk to 1 out of 4 different people. Once somebody mentions a goblin (which it's random on who will) you can then proceed to whatever the next step is.

**Comment by jertje260** [comment]
ran into this as well, its either Hans, The Cook, Father Aereck or Bob

**Comment by kylestev** [comment]
Looks like it was fixed in 4f8493887bad477c0f4b6c910bc8b6fdc71225e7

**Comment by Zoinkwiz** [comment]
This should now be fixed with the most recent release on the plugin hub. It's not perfect as it will indicate both Cook and Aereck as I'm not certain of what their respective values are. At least now it won't be incorrectly indicating things.
