### ISSUE TITLE
Typo in lunar diplomacy

### ISSUE THREAD

**Issue by Senis6** [Zoinkwiz/quest-helper#332]
In the Chance challenge of the lunar diplomacy quest the word ''dice''is missspelled as ''die''

**Comment by Kerpackie** [comment]
Is there multiple dice? If so, die is the plural and would be correct. 

I'll look into it and confirm, and fix if required :)

**Comment by Zoinkwiz** [comment]
Die is the singular of Dice, and the context is `Flip the centre west die.` (and other such directions) so looks correct to me. If there's a usage which should be plural let me know, but I'll close this for now.
