### ISSUE TITLE
Incorrect panel details label for Karamja Medium Diary

### ISSUE THREAD

**Issue by andrewjmetzger** [Zoinkwiz/quest-helper#333]
With plugin v 2.1.0 from the RL hub, the Karamja Medium Diary helper panel shows "Easy Diary".

Image:
![image](https://user-images.githubusercontent.com/590246/120831741-df91b300-c52d-11eb-8388-a1c7a64170ef.png)

Discord discussion: https://discord.com/channels/772056816242130964/776427467560321034/850410159326232636

**Comment by Zoinkwiz** [comment]
Fixed with https://github.com/Zoinkwiz/quest-helper/commit/44f9a789707da77086696cd952a8fa88ff3ce20e#diff-3c13b1b26d1b7ccbdc9484c49530b4315dbd30f21b759db623e2554d0050fa27.
