### ISSUE TITLE
Issue with diary guide

### ISSUE THREAD

**Issue by opiethesouless** [Zoinkwiz/quest-helper#352]
Hello, I want to say first that I love tjhe quest helper addon!  

I have run into an issue with the diary guide portion, When I try and do the first step of the karamja easy diary "travel to port sarim from musa point with the customs officer" it will not move to the next step. Also It would be cool to add a skip step function for instances like this. I hope this helps and thank you for your time and awesome addon!

**Comment by Kerpackie** [comment]
Hey! Thanks for the report, this has been fixed in Commit: b67a0ad61c1e2b990839a9e28222c342a775e694 there was an oversight with a previous commit which messed with some back-end logic, which has been fixed now!
