### ISSUE TITLE
Miniquest "Architectual Alliance", Step location wrong (shayzien)

### ISSUE THREAD

**Issue by merlinmarijn** [Zoinkwiz/quest-helper#368]
the step:
"talk to shayda north of the shayzien bank" is wrong, Its placed in the shayzien encampment, while the npc that you need to talk to is in the area BELOW the campment.

Here are screenshots of where it says compared to where she is,
https://cdn.discordapp.com/attachments/772056861934354433/855372392818016276/unknown.png
https://cdn.discordapp.com/attachments/772056861934354433/855372509104701490/unknown.png

**Comment by Zoinkwiz** [comment]
Thanks, should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/09f428cfcd4c787b203a951fc2bf6bdd11e23dc4#diff-be04cff44ec14f8f6df96a6bc75481e31bf2a60e916915b1ebb1e3972e04c455
