### ISSUE TITLE
My Arm's Big Adventure missing spade in step Troll farming

### ISSUE THREAD

**Issue by glebocki** [Zoinkwiz/quest-helper#370]
After the fight with the bigger bird, we need to give the troll a spade. It's not on the list of items required. And lepricone is gone at that point.

Alright If I teleport out and come back the lepricone is back :(

Still I can take a look and add it to the code. Since I'd like to help you out ;)

**Comment by Zoinkwiz** [comment]
Fixed now in https://github.com/Zoinkwiz/quest-helper/commit/703680824ff9e7152e79af0d080322f58a9a1ef5#diff-65da6a48f29d2298be0b569d81cb11b8cb7feae29bd84973aa1b4d44c1db0252, thanks!
