### ISSUE TITLE
Quest "Tale of the Righteous" Incorrect quest marker

### ISSUE THREAD

**Issue by ExcessiveToast** [Zoinkwiz/quest-helper#373]
The quest marker to start the quest "Tale of the Righteous" is in the incorrect location.  Phileas Rimor, the quest giver, is located in the main Shayzien encampment, next to the pub.  See photo of map, showing accurate location of quest start.  
![Tales of the Righteous](https://user-images.githubusercontent.com/86203456/122684373-078e4100-d1d3-11eb-8986-11171c2070de.PNG)

**Comment by ExcessiveToast** [comment]
In addition, the quest marker for the NPC "Lord Shiro Shazien" is also in the incorrect spot.  He is located in the large tent on the west side of the Shazien encampment, upstairs.  See attached photo for map guide.
![Tales of the Righteous](https://user-images.githubusercontent.com/86203456/122684585-2e994280-d1d4-11eb-9b7c-b1d52b8996e1.PNG)

**Comment by SturgeoOrca** [comment]
6/21/2021
Issue still present - Lord Shiro's and Phileas Rimor's location are still incorrect. OP's picture reflecting incorrect locations and markers is still accurate.

**Comment by Zoinkwiz** [comment]
Should be fixed now in the main game with https://github.com/Zoinkwiz/quest-helper/pull/363, thanks
