### ISSUE TITLE
Quest X Marks the Spot

### ISSUE THREAD

**Issue by geekyhuff** [Zoinkwiz/quest-helper#374]
I'm on my fresh HCIM and for the quest X Marks the Spot the general store location for Lovakengj provided by the quest helper plugin is incorrect. I believe it got moved a few updates ago 
![1234](https://user-images.githubusercontent.com/52847956/122692587-f6115d00-d203-11eb-9a42-23e2386ed1de.png)
the following screenshot shows the quest helper location and the current general store location is a bit north.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/pull/381
