### ISSUE TITLE
Death to the Dorgeshuun step missing

### ISSUE THREAD

**Issue by DriesWambacq** [Zoinkwiz/quest-helper#38]
In Death to the Dorgeshuun, zanik needs to find a trapdoor for you. There is a prerequisite step missing for this to happen. You first need to talk to Johanhus Ulsbrecht (4 - 3) and then Zanik can find the trapdoor.

**Comment by Zoinkwiz** [comment]
Hi, this is fixed in https://github.com/Zoinkwiz/quest-helper/commit/5a50f88553c10a0e9098caaef38fd603c1553b5c, currently waiting on the Runelite team to review changes for it to be live.
