### ISSUE TITLE
Quest Helper not working

### ISSUE THREAD

**Issue by Patlegend2021** [Zoinkwiz/quest-helper#384]
@Zoinkwiz 

- Switched on Quest helper and its not changing the colors of text when i have that item or skill or quest requirement done.

**Comment by Zoinkwiz** [comment]
@Patlegend2021 can you please share your logs so I can see what happened? After that, try closing and opening Runelite and see if that fixes it for you.

- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS to get your logs.

**Comment by Patlegend2021** [comment]
@Zoinkwiz  oh it just fixed itself with an update :) thank you

**Comment by Zoinkwiz** [comment]
Could you still share the logs? Would be good to see what caused it to happen.

**Comment by Patlegend2021** [comment]
[client.log](https://github.com/Zoinkwiz/quest-helper/files/6732852/client.log)

**Comment by Zoinkwiz** [comment]
Thanks, a fix to stop this should now be live!
