### ISSUE TITLE
Fight Arena

### ISSUE THREAD

**Issue by NicholasDreyer** [Zoinkwiz/quest-helper#386]
In the section, "Fight!", the "Talk to Hengrad." task does not get highlighted and skips to the section where you kill the scorpion.

**Comment by CyrexProgramming** [comment]
I just did it right now at 1250 PM UTC ( and at the part where you're supposed to talk to Hengrad after you beat the Ogre, it told me to "Talk to Sammy". After talking to Hengrad, the quest helper continued properly for me.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/76e3c34159de5fd0ece27e7f0fbe3bcf047ca0e9, thanks for raising.
