### ISSUE TITLE
The digsite quest

### ISSUE THREAD

**Issue by Avenandi** [Zoinkwiz/quest-helper#402]
on the step where you need to grab a specimen jar and rock pick, the guide jumps over the part where you need to grab it and only wants you to grab a rock pick, only that grabbing a rock pick does not update the quest until the player himself looks up that he need to grab a specimen jar from the south cupboard whereupon the quest will update.

TL:dr the digsite guide jumps over the step of grabbing the specimen jar.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/af395fbc8fd9a74b6aa989de688e0afe194279b4, thanks.
