### ISSUE TITLE
Lunar Diplomacy: memory challenge displays incorrect path

### ISSUE THREAD

**Issue by nsilvestri** [Zoinkwiz/quest-helper#41]
On the memory challenge for Lunar Diplomacy, the Path 7 from the [OSRS Wiki guide](https://oldschool.runescape.wiki/w/Lunar_Diplomacy) was drawn on screen, but the solution was actually Path 10. Furthermore, it seems like only 8 of the 10 (and possibly more) paths are currently supported.

**Comment by Zoinkwiz** [comment]
Hey, good spot, I've fixed broken checks for paths 1/2 and added paths 9/10 with https://github.com/Zoinkwiz/quest-helper/commit/cc156a2716099be59d54b79e03ce77dc29c0d4f3.
