### ISSUE TITLE
Achievement diaries not displaying correctly

### ISSUE THREAD

**Issue by Whal93** [Zoinkwiz/quest-helper#410]
the achievement diaries are not showing up in my meets reqs which is correct because i dont. but there is a few diaries that i do meet the reqs for and they arent showing anywhere.

**Comment by Zoinkwiz** [comment]
Hey @Whal93 could you let me know which diaries you have reqs for which aren't showing?

**Comment by Whal93** [comment]
hey! for me right now, i have the reqs for kandarin med, karamja med and western provinces med. 

kandarin med has now appeared but the other 2 are still missing.

if i click to show every quest and diary even without the reqs for. most of the diaries are missing.
falador, fremmy, kandarin and karamja are the only diaries showing. which are all correct, the ones i dont have the reqs for are there. every other diary is missing from the full list.

thanks!

**Comment by beau-witter** [comment]
Same problem
![image](https://user-images.githubusercontent.com/26094186/133168905-5574c5ac-3c70-4032-aba5-987be6e2c0f6.png)
I have several diaries that _could_ show up when set to "Show All" but it just seems to pick one arbitrarily to show.

**Comment by Whal93** [comment]
Yes this is still an issue. Doesn't show certain diaries at all even on the
show all

**Comment by Zoinkwiz** [comment]
Those have been diaries that didn't exist at the time on the helper, thus they didn't appear.
