### ISSUE TITLE
Demon Slayer

### ISSUE THREAD

**Issue by Andrewcapo** [Zoinkwiz/quest-helper#42]
For demon slayer the plugin only lists 25 bones as an item requirement. The quest also requires 1gp(you have to give gypsy aris 1gp when you start the quest) and a bucket of water(it does show you where to pick up a bucket, though. So not really a big deal). Edit: Also found the quest doesn't list food+armor and varrock/draynor teleports. And in the enemies to defeat section Delrith isn't listed.

Just wanted to add I'm really liking the plugin quite a bit, and I hope you continue working on it. It's great! I'll continue to report any issues I come across. Thanks!!

**Comment by Zoinkwiz** [comment]
Thanks, I've added all of that with https://github.com/Zoinkwiz/quest-helper/commit/017c56a8633610e0c5a953ee6583df6903f08162. Glad you've been enjoying it, appreciate any reports on issues you find!
