### ISSUE TITLE
Misspell in "The Feud" quest

### ISSUE THREAD

**Issue by zamburge** [Zoinkwiz/quest-helper#429]
In the starting out section of **The Feud** "Al Kharid" is spelled "Al Kahrid"

Questhelper is amazing thanks!

**Comment by zamburge** [comment]
It is spelled the same way in the finishing off section as well

**Comment by rileyyy** [comment]
@Zoinkwiz would you please be kind enough to resolve this issue manually?  It was resolved with PR #431
