### ISSUE TITLE
Quest helper missing.

### ISSUE THREAD

**Issue by invid5** [Zoinkwiz/quest-helper#432]
I recently reinstalled my runelite client, and quest helper is no longer listed in the third party plugins. It is also missing from "https://runelite.net/plugin-hub/" when I went to manually search for it.

**Comment by SashaRyder** [comment]
Ditto, I also can't see it. it's possible that its been removed off the runelite plugin hub for whatever reason

**Comment by jamesallan97** [comment]
This has happened to be me too :( right during a quest. i hope it is back up soon.

**Comment by SashaRyder** [comment]
Just checked the discord, looks like its broken due to a runelite update. They're fixing it now.

**Comment by jamesallan97** [comment]
Amazing! thank you. hopefully not too long

**Comment by invid5** [comment]
Thank you, problem solved then.

**Comment by jamesallan97** [comment]
How long will it take do you think?
