### ISSUE TITLE
Fremennik Trials Quest

### ISSUE THREAD

**Issue by 1405949G** [Zoinkwiz/quest-helper#442]
Following the quest helper, I got stuck at Manni's task. Everytime I put the strange object into the pipe, it kept asking me to get another one from the council woman. When the actual step is supposed to be to take the keg of beer and use the low alcohol beer on it, to create the explosion scene. This step is not included in the quest helper. Kindly help to add it in so that future users do not face this issue. Thank you!

**Comment by Zoinkwiz** [comment]
This should be fixed now in https://github.com/Zoinkwiz/quest-helper/commit/d7d7194d6986bcff21b5b72ab11dbf18c60040d9
