### ISSUE TITLE
Missing required item during "The Feud" quest

### ISSUE THREAD

**Issue by WesleyM77** [Zoinkwiz/quest-helper#448]
In the "Rising up" section of the quest, a bucket is required in order to pickup the camel dung.

**Comment by Kerpackie** [comment]
When you don't have a bucket, it should redirect you to pick up the bucket inside the building where the dung is located, hence it will not prompt you on the side panel.

**Comment by WesleyM77** [comment]
Oh, I must've missed that. I don't remember seeing the prompt, but now, it's been more than a month. Closing now, thanks.
