### ISSUE TITLE
The Digsite quest

### ISSUE THREAD

**Issue by TheRealStunts** [Zoinkwiz/quest-helper#449]
the step where it asks me to search the cupboard for a rock pick, it wont progress to the next step which should be to search for a specimen jar, which doesnt even show up in the list of steps.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/af395fbc8fd9a74b6aa989de688e0afe194279b4, thanks.
