### ISSUE TITLE
Murder Mystery's tracking gets stuck at the investigate window option, not progressing at all after it

### ISSUE THREAD

**Issue by DanGM96** [Zoinkwiz/quest-helper#45]
It seems that there are other issues with the tracking as well but can't remember right now

**Comment by Zoinkwiz** [comment]
I've added all the remaining thread paths with https://github.com/Zoinkwiz/quest-helper/commit/a5edc77b7b0c6bcfcfc99919314ea419e3af7d96, so hopefully that should fix it. In general I'd like to improve the second half of Murder Mystery, so I'll raise an issue regarding specifically that.
