### ISSUE TITLE
Curse of the Empty Lord

### ISSUE THREAD

**Issue by csandman** [Zoinkwiz/quest-helper#452]
The fifth ghost in the wizard tower of "Curse of the Empty Lord" is not being targeted properly by quest helper.  The arrow on the minimap is bouncing around pointing off the map like so:

![image](https://user-images.githubusercontent.com/9214195/133732957-1c69db41-2130-4b39-9b3f-eeb2257a9fde.png)

And the NPC is not highlighted:

![image](https://user-images.githubusercontent.com/9214195/133732989-13f00ca9-8468-4faa-acd6-6f8f2a26da0f.png)

**Comment by Zoinkwiz** [comment]
Fixed in https://github.com/Zoinkwiz/quest-helper/commit/e21e1ce92ec6590a65487958a0057bf41ffbb536.
