### ISSUE TITLE
Suggestion/Fix: Below Ice Mountain Marley

### ISSUE THREAD

**Issue by robuhde** [Zoinkwiz/quest-helper#468]
I'm unsure what your standards dictate, but looking at the varbit requirements for Marley in Below Ice Mountain suggests that you do not have to speak to Marley prior to getting the recipe.

If the goal is for "fast" completion, or minimizing steps (literally) taken, should speaking to Charlie the Tramp next to the Blue Moon Inn replace that step?

**Comment by Zoinkwiz** [comment]
The goal isn't to skip story with the helper, thus why it goes to Marley being a req. Thanks though, it's a good spot 😄
