### ISSUE TITLE
Fremenik Trials Issues

### ISSUE THREAD

**Issue by Noaaan** [Zoinkwiz/quest-helper#473]
Extending on issue #457 the Fremenik Trials quest doesn't really benefit from the quest helper. Some of the steps are misleading, the helper constantly needs to be refreshed, and generally this quest needs a re-write.
Even as simple as writing that the helper needs to be refreshed a lot for this quest in the helper would be useful to the player, so they can at least go to the quick guide itself.

**Comment by Zoinkwiz** [comment]
This should be fixed now, if anyone encounters the above issue again please let me know.
