### ISSUE TITLE
Merlin's crystal should tell you to bring combat equipment and food before hiding in the crate

### ISSUE THREAD

**Issue by davidponton** [Zoinkwiz/quest-helper#477]
Just hid in the crate and got smacked a bunch by the knights, ran past them, then found out this is the part I have to fight Mordred and had to tele out because I definitely wasn't prepared for that

**Comment by Zoinkwiz** [comment]
Added combat gear to overall reqs in https://github.com/Zoinkwiz/quest-helper/commit/bcd7f7ad8dcebb7688d9e8336c26529e93e3b89f
