### ISSUE TITLE
RFD: Evil Dave spice detection bug

### ISSUE THREAD

**Issue by Nightfirecat** [Zoinkwiz/quest-helper#485]
During the Evil Dave portion of Recipe for Disaster, the overlay will not always be accurate for the amount of spice collected from hellrats.

For instance, my most recent runthrough of the quest called for:
* 1 red
* 3 orange
* 3 brown
* 1 yellow

With the following items in my inventory, it did not recognize that I had sufficient brown and orange spice:

1. Orange spice (4)
2. Red spice (3)
3. Yellow spice (4)
4. Brown spice (3)
5. Orange spice (1)

**Comment by Zoinkwiz** [comment]
The helper no longer lets the player know how much spice they should have, so closing this for now.
