### ISSUE TITLE
Demon Slayer bugged

### ISSUE THREAD

**Issue by kiljayden** [Zoinkwiz/quest-helper#50]
No info on the side panel for Demon Slayer, arrows and dialogue options still show up.

**Comment by Zoinkwiz** [comment]
Hi, thanks for raising this, should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/56f16f0e0f8e04d3e9d38c1cd71c299b42da79f0.

**Comment by kiljayden** [comment]
Awesome! Thank you.
