### ISSUE TITLE
Quest helper addtion to The Fremennik Trials

### ISSUE THREAD

**Issue by asundstrom** [Zoinkwiz/quest-helper#515]
Hello,
I just wanted to leave a comment on the quest guide for The Fremennik Trails.

In the step under Manni's task:
Is it possible to add the second to last step before the step "Talk to Manni the Reveller to cheat in the competition." to add another step which is an intended game mechanic of how you cheat. The step could be called "Use the _low acohol keg_ on the _keg of beer_" which is the requirement in order to cheat. The quest guide right now loops back to the second step under Manni's task as of now.

Thank you for your great work with the Quest Helper
Best Regards

**Comment by Zoinkwiz** [comment]
Hey, this should now be fixed with release 2.6.1.
