### ISSUE TITLE
Prince Ali Rescue quest flaws

### ISSUE THREAD

**Issue by sidvanvliet** [Zoinkwiz/quest-helper#53]
Hi!

Whilst doing the Prince Ali Rescue quest on my ironman, I noticed a few flaws in the quest helper:

1st flaw: 
The "Key imprint" step doesn't tell you to bring a bronze bar, which is required to complete the step.

2nd flaw:
The "Talk to Leela east of Draynor Village" dialog doesn't appear to display what dialog options to choose, also doesn't tell you to get a skirt and rope.

I might be able to submit a pull request to fix the flaws noted above this weekend.

**Comment by Zoinkwiz** [comment]
Thanks for raising, I've improved the prompts for items in general for the quest. What chat option are you referring to with Leela? As far as I'm aware there's no dialog choice required during the quest with her.

**Comment by sidvanvliet** [comment]
You're right, my bad. You don't have to select any choice during that dialog.
