### ISSUE TITLE
One Small Favour Doesn't prompt to pick up Pigeon Cages

### ISSUE THREAD

**Issue by SirXen0** [Zoinkwiz/quest-helper#534]
One Small Favour doesn't have any prompts to pick up or pre-requisite any pigeon cages during the quest when you need 5 near the end of the quest.

**Comment by Smileynator** [comment]
Now it does, but it doesn't show me why, so i ended up dropping the cages in error before i got to the point where they were needed :D I thought "plugin must be trippin".
