### ISSUE TITLE
Kandarian Medium Diary - Catch and cook a Bass in Catherby

### ISSUE THREAD

**Issue by jeff06** [Zoinkwiz/quest-helper#537]
The ui is pointing on a small fishing net spot. It should point on a big fishing net spot

**Comment by jeff06** [comment]
I have no clue how to get the correct FishingSpot id, but the problem is here -> 
catchBass = new NpcStep(this, NpcID.FISHING_SPOT_1518, new WorldPoint(2837, 3431, 0),
			"Catch a bass.", bigFishingNet);
		catchBass.addAlternateNpcs(NpcID.FISHING_SPOT_1520);

**Comment by Obasill** [comment]
Resolved thanks for the feedback!
