### ISSUE TITLE
Buying Initiate armour for Falador medium diary costs 20k, not 14k

### ISSUE THREAD

**Issue by Nightfirecat** [Zoinkwiz/quest-helper#539]
In both versions of Sir Tiffy Cashien's store, the price of the armour pack is 20k, not 14k. https://oldschool.runescape.wiki/w/Sir_Tiffy_Cashien

**Comment by Zoinkwiz** [comment]
fixed with 64926609bcc3dc2a4b12df8ea37e5c471da8e3c3
