### ISSUE TITLE
Ghost Ahoy Quest Text Missing

### ISSUE THREAD

**Issue by davidmoed** [Zoinkwiz/quest-helper#54]
The side instructions and sections are missing for the quest.  The highlighted items and on screen arrows still work as do the necessary items in the instructions window. Restarting the quest did not help.

This was noticed on an account playing Trailblazer league.
![Screen Shot 2020-11-06 at 11 20 11 PM](https://user-images.githubusercontent.com/20621811/98415844-b045c100-2086-11eb-865b-331fb5002fce.png)

**Comment by Zoinkwiz** [comment]
This should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/ddbcaef137d4f2289aecf474c6357c7e1506afa5.
