### ISSUE TITLE
quest helper

### ISSUE THREAD

**Issue by KerberosWolf** [Zoinkwiz/quest-helper#553]
i have quest helper install onto runelite and it says that it installs. but when the install starts, it stops around, 0.7% out of 2.2% of the installation and then acts as if it installed but when i go to the plugin drop down bar and look at the plugins i have  quest helper is not there and it is not on the side bar like it was before idk what happen but now i cant use it ive removed and re-installed it multiple times waited a few days and tried again but nothing has changed  and i dont know what to do any more i would appriecate your help please i dont really know anything about runelite or how things work because i just got it recently  and your plugin helped me out alot for a few days before the last update... every one ive asked hasnt been able to help me with this

**Comment by Zoinkwiz** [comment]
Hi @KerberosWolf is this still an issue for you?
