### ISSUE TITLE
Depths or Despair missing quest requirement

### ISSUE THREAD

**Issue by Justlfied** [Zoinkwiz/quest-helper#561]
![image](https://user-images.githubusercontent.com/57233854/141639100-2d9c3927-4975-4807-a9f6-557a81f9f333.png)
![image](https://user-images.githubusercontent.com/57233854/141639367-76da070d-7f63-483c-84ca-54fa07959c4f.png)

Its missing the X Marks The Spot quest req

**Comment by Obasill** [comment]
That's interesting, client of kourend requires that you've completed x marks the spot. At least according to the wiki. Regardless, I'll fix it. Ty for the feedback!
![image](https://user-images.githubusercontent.com/13607196/142826871-d9f6d969-e02c-41b9-b299-46967c2ec595.png)
