### ISSUE TITLE
Quest Helper Log on Galvek covers whole screen

### ISSUE THREAD

**Issue by bdixon95** [Zoinkwiz/quest-helper#572]
We actually neeed to be able to see the chat box. Perhaps don't let the plugin cover the entire screen. Makes no sense. Make it wider, not longer.

**Comment by Zoinkwiz** [comment]
You can choose how wide it is @bdixon95 by dragging it out. I can't control that. I will make the on-screen text reduced though as many people don't know they can alt-drag the size of it though.
