### ISSUE TITLE
Varrock Hard Diary - Trade for a Spottier Cape

### ISSUE THREAD

**Issue by KUR0N3K0H** [Zoinkwiz/quest-helper#573]
The 66 hunter requirement for equipping a spottier cape is not boostable. 
I currently have 63 hunter on my account and I boosted it to 66 with a hunter potion, but I was unable to equip the cape. 
Currently in quest helper the hunter requirement is listed as "66 Hunter (boostable)"

**Comment by Obasill** [comment]
Ah my bad, I did change this but only for the general reqs panel and not the specific task one. I just opened a PR to resolve this.
