### ISSUE TITLE
Death to the Dorgeshuun skipped step

### ISSUE THREAD

**Issue by jasonro93** [Zoinkwiz/quest-helper#578]
On the "Foiling H.A.M." quest guide, the guide automatically skips the first step ("Talk to Zanik under the Lumbridge Castle.")  It set up a marker on the crates in the farm north of Lumbridge right after I finished reviving Zanik at the Tears of Guthix.  It wasn't a big deal to figure out, but if somebody is following the quest markers rather than reading the guide step-by-step, such as myself, then will end up at the farm trying to figure out why they can't interact with the crates.

(Talking to Zanik in Lumbridge is apparently required for the quest to proceed.)

**Comment by Zoinkwiz** [comment]
This is an issue with the varbit used to detect if Zanik is with you or not. I will need to look at if there's a better way to detect Zanik following you or not.
