### ISSUE TITLE
 bug in a taste of hope

### ISSUE THREAD

**Issue by mjkiyoi69** [Zoinkwiz/quest-helper#58]
during the step after making the potion where you use it on the door, it says something isn't right and the quest is closed and I can't reopen. have gotten so many quests completed with your plugin (22 remaining quests) after manually continuing after I was able to open the quest again and finished smoothly thanks so much! (21)

**Comment by Zoinkwiz** [comment]
Hey, I hope that https://github.com/Zoinkwiz/quest-helper/commit/7fdd19bc4a852055ef18f88a746f819d2aee0dc0 should fix this. Thanks for raising this issue!
