### ISSUE TITLE
Ardougne Diaries are non existent 

### ISSUE THREAD

**Issue by Jabbari1** [Zoinkwiz/quest-helper#588]
![Screenshot 2021-12-02 115329](https://user-images.githubusercontent.com/95435337/144467053-25991cb2-8904-4030-87bd-1960d86d72ae.jpg)

Hey! I love this app you have saved me from the normal frustrations of osrs so much! 

Ardougne diaries have never been available for me, the other diary helpers were wonderful . Thanks so much!

**Comment by Obasill** [comment]
Glad you're liking them, currently the Ardy diaries are under review and should be in the helper soon™
