### ISSUE TITLE
Optimal Ordering - Desert Medium Diaries shows before Enakhra's Lament

### ISSUE THREAD

**Issue by tr33s** [Zoinkwiz/quest-helper#609]
The Camulet from Enakhra's Lament is required for Desert Medium Diaries, but the optimal ordering shows the diaries first:
![image](https://user-images.githubusercontent.com/10179913/146314231-65d640a8-fe59-4ade-a861-e0ecd201ae08.png)

![image](https://user-images.githubusercontent.com/10179913/146314344-f101c841-9b1d-488e-8f4e-e6de6a487077.png)

**Comment by binury** [comment]
Yeah `Desert Medium Diaries` isn't even on [the list](https://oldschool.runescape.wiki/w/Optimal_quest_guide/Ironman) where the [optimal ordering](https://github.com/Zoinkwiz/quest-helper/blob/10886117d52e3ff34a46bac3aa79f04e8fae965b/src/main/java/com/questhelper/panel/questorders/QuestOrders.java#L401-L478) is supposedly pulled from 🤔
