### ISSUE TITLE
Quest Helper making Runelite very laggy

### ISSUE THREAD

**Issue by blaster73** [Zoinkwiz/quest-helper#61]
As of last night November 10th, 2020 Quest Helper would make Runelite very laggy after a short amount of time of Runelite being launched. The only way to stop it was to uninstall Quest Helper

It's a great plugin, I've enjoyed it in Leagues since I already have a quest cape on my main. Please let me know when you fix it so I can install it again. Thanks! 

Email:
blaster73@hotmail.com

**Comment by Zoinkwiz** [comment]
Hi @blaster73 , would you be able to provide more details please? For example, was it only laggy whilst the plugin was active, or just always? If not active, had you recently used it, and if so which quest?

Also, were you in a specific area when you were seeing lag? Any details appreciated so I can investigate.

**Comment by Zoinkwiz** [comment]
As I've not heard back, nor had anyone else mentioning this, I'm going to assume this was a one-off issue, potentially not related to the helper. If you have more details so I can look into it please do put them here. Until then, I'll be closing this issue.
