### ISSUE TITLE
Grand exchange quick buy button shows the wrong quest items

### ISSUE THREAD

**Issue by Scape070** [Zoinkwiz/quest-helper#610]
It shows this same list of items for every quest, without including the correct ones.

![ScreenShot_20211216162231](https://user-images.githubusercontent.com/95359977/146400471-b5863174-2323-41df-9870-655e5442bd68.png)

**Comment by Zoinkwiz** [comment]
Also do you have any other plugins enabled @Scape070 ?

**Comment by Zoinkwiz** [comment]
My hunch is it might be as you have 'fuzzy fallback' enabled in the Grand Exchange plugin. If you turn that off does it then work?

**Comment by Scape070** [comment]
I indeed had "fuzzy fallback" enabled in the Grand Exchange plugin, and setting it back to "default" search mode fixed it! Now it's working perfectly. Only when I set the Grand Exchange plugin search mode to "fuzzy fallback" or "fuzzy only" does it give the problem in the screenshot. But for now on "default" mode working perfectly.

**Comment by Zoinkwiz** [comment]
This should be fixed with the fix  in the core runelite plugin from https://github.com/runelite/runelite/issues/14499.
