### ISSUE TITLE
Death to the Dorgeshuun - Missing step

### ISSUE THREAD

**Issue by Dgc2002** [Zoinkwiz/quest-helper#63]
In the `Infiltrate the H.A.M.` sub-section there is a missing step. Without this step Zanik will not notice the trap door.  
  
Here is the sub-section for reference
![image](https://user-images.githubusercontent.com/3957791/99041345-be994e80-2558-11eb-8b07-701252cb6972.png)

The step can be seen [in the Wiki's quick guide](https://oldschool.runescape.wiki/w/Death_to_the_Dorgeshuun/Quick_guide) listed as  
  
> Talk to Johanhus Ulsbrecht southeast of the stage. (Chat 4•3)  
  
and in [Slayermusiq1's guide](https://youtu.be/oySK9ynBkT0?t=371).  
  
This step either belongs before the "Go stand at the south of the stage..." step or it should replace that step.

**Comment by Zoinkwiz** [comment]
Hey, https://github.com/Zoinkwiz/quest-helper/commit/c5bb972e95e870d3e6c086954bbd2a765a72e7a0 should fix the sidebar issue. Did the top-left box also incorrectly skip this step, or is it just missing from the sidebar?

**Comment by Dgc2002** [comment]
Unfortunately I don't remember if the top left box was missing this step or not. To be honest the only time I notice that box is when there's colored text in it, otherwise it's so transparent/subtle it just blends in.

**Comment by Zoinkwiz** [comment]
No worries, from what I've tested this should hopefully fix this then, thanks for raising the issue!
