### ISSUE TITLE
Wilderness hard achievement diary smith adamant scimitar requires 2 adamant bars, not one

### ISSUE THREAD

**Issue by BearsOnABus** [Zoinkwiz/quest-helper#677]

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/150086280-994ab51e-e049-4f1f-ad1c-0cb8a9d34c1f.png)

![image](https://user-images.githubusercontent.com/41973452/150086515-bd721ab8-e14a-4d6c-abd2-c62dfbebfe72.png)
