### ISSUE TITLE
The Fremennik Isles Quest a decent amount of missing/bad info

### ISSUE THREAD

**Issue by scrapmuffin** [Zoinkwiz/quest-helper#693]
The quest requires you to split 3 logs onto a woodcutting stump however the quest helper only states cut down arctic pines nearby.
woodcutting the arctic  pines require 54 woodcutting which isnt stated in the general requirements
and to split the logs you need 56 woodcutting which isnt stated either
There is also a missing skill requirement for crafting which is lvl 43
also the raw tuna is not needed had it in my inventory from the beginning and at the end its still there.
Also at the end of the quest its not 1 exp lamp but 2 both 10k in combat
https://i.imgur.com/eFviyIo.png
https://i.imgur.com/skr6pbr.png
https://i.imgur.com/uuXsIKO.png
https://i.imgur.com/gOnnlW6.png
https://i.imgur.com/QVq6r9J.png
https://i.imgur.com/QwUe9Dn.png

**Comment by Sagnip** [comment]
Also another small thing that isn't as big an issue, but irritating, this part states the items can be gathered south-east OF rellekka, however the farm is IN south-east rellekka (not outside) so, it's easy to blow half an hour looking around for the farm thinking it's not in the town xD

![image](https://user-images.githubusercontent.com/16483501/154431485-1a32b913-5dcc-4e48-9ebf-c5dcd34339f5.png)

**Comment by kayjay010101** [comment]
> Also another small thing that isn't as big an issue, but irritating, this part states the items can be gathered south-east OF rellekka, however the farm is IN south-east rellekka (not outside) so, it's easy to blow half an hour looking around for the farm thinking it's not in the town xD
> 
> ![image](https://user-images.githubusercontent.com/16483501/154431485-1a32b913-5dcc-4e48-9ebf-c5dcd34339f5.png)

Actually that says "IN the south east of Relekka", which is correct. It does not say just south east of Relekka.
