### ISSUE TITLE
A Tail of Two Cats

### ISSUE THREAD

**Issue by Raisoshi** [Zoinkwiz/quest-helper#7]
Hi! Been enjoying the plugin a lot.

On the A Tail of Two Cats guide, it tells you to talk to Reldo in the Varrock Museum, but he's in the Castle's library, not the museum. The quest marker is right, but the text is wrong.

Just so you guys can fix so others don't take an unecessary trip to the museum like I did lol

**Comment by Zoinkwiz** [comment]
Hey, thanks for raising this, I've got a fix in the above PR #8 . Please do let me know if you come across any further issues, glad you've been enjoying it so far!
