### ISSUE TITLE
Add hyperlink to wiki entry for quest selected

### ISSUE THREAD

**Issue by mmccoy37** [Zoinkwiz/quest-helper#70]
When viewing a quest in quest helper it can be helpful to pre-read the wiki incase there are other details such as maps, recommended teleports, etc. Having a handy dandy link would be a++

**Comment by nnapolitano** [comment]
I will take a look into adding this feature

**Comment by nnapolitano** [comment]
Work on this feature is in progress, @Zoinkwiz you can assign to me so no one else picks it up.

**Comment by nnapolitano** [comment]
PR #255 opened
