### ISSUE TITLE
This should say southwest

### ISSUE THREAD

**Issue by stephan-baulch** [Zoinkwiz/quest-helper#701]
https://github.com/Zoinkwiz/quest-helper/blob/5dcb1ff108a28a5da5174dc33e8bb17d9efea86f/src/main/java/com/questhelper/quests/legendsquest/LegendsQuest.java#L675

**Comment by stephan-baulch** [comment]
proof:https://oldschool.runescape.wiki/w/Vanilla_pod

**Comment by Felanbird** [comment]
@Zoinkwiz This needs to be manually closed since you merged the duplicate PR that didn't have a linked issue.
