### ISSUE TITLE
Cabin Fever - Repeated step text

### ISSUE THREAD

**Issue by RobertRR** [Zoinkwiz/quest-helper#72]
The text "Return the plunder to the chest in Bill's hull" repeats 4 times in the instructions panel under the "Plunder the pirates" section of the quest

**Comment by Zoinkwiz** [comment]
Should be fixed by https://github.com/Zoinkwiz/quest-helper/commit/9eb3d1f118f26c8f3044ed8465b709c08ca395ee, thanks for raising.
