### ISSUE TITLE
Legends' Quest: Add binding book to item requirements

### ISSUE THREAD

**Issue by Butterscup** [Zoinkwiz/quest-helper#735]
Upon getting to the section "Freeing Ungadulu", I deposited everything into my bank and withdrew items using the quest helper bank filter. I made it all the way to Ungadulu only to discover that I needed the binding book that I acquired in a previous step of the quest. Please add the binding book to the item requirements for this step of the quest.

**Comment by gare-bear** [comment]
@Butterscup Working on a PR as we speak. I want to include a few other changes and also verify all item requirements and detection are accounted for. I'll be completing the quest in the process so might take a little bit of time to complete testing. I'll circle back to this issue with a PR once I'm done.

**Comment by gare-bear** [comment]
Just submitted PR #740. This adds the item requirements for the binding book.
Tested it myself while completing the quest.

**Comment by PJGJ210** [comment]
Still seeing this issue 4/27/2022 after March 25th merge.

**Comment by gare-bear** [comment]
Post up a screenshot?

**Comment by PJGJ210** [comment]
Logged into an alt (completed since) and I now see it
![image](https://user-images.githubusercontent.com/16944807/165964393-4e5f7e23-e872-46b3-bf0f-f87278af39f3.png)
