### ISSUE TITLE
quest Helper not showing up in plugin list

### ISSUE THREAD

**Issue by neprulers** [Zoinkwiz/quest-helper#741]
the quest helper plugin stopped working suddenly. I cant see it on the runelite side task bar. any help

**Comment by McSheehy** [comment]
Ditto. 
I assume it's new patch related. 100% the plugin I'm most reliant on, without even being aware.

**Comment by jeraziah** [comment]
Ditto

**Comment by Fre4ked** [comment]
Same here

**Comment by Sharpienero** [comment]
It's back in the list now. 

@jeraziah @Fre4ked @McSheehy @neprulers

**Comment by neprulers** [comment]
Yes it is back i can see it now. This plugin is very helpful
