### ISSUE TITLE
Change the Shield of Arrav quest requirement listing for Heroes' Quest 

### ISSUE THREAD

**Issue by Kuurse** [Zoinkwiz/quest-helper#748]
The quest requirement for Heroes' Quest  concerning Shield of Arrav is marked as Shield of Arrav - Phoenix Gang, steering all the players into joining the Phoenix Gang and creating a shortage of Black Arm Gang members (there is litterally a waiting list and players are bidding for BAGs in the OSRS SoA clan chat).
It would be nice to see either of the quests marked as a requirement for Heroes' Quest.

**Comment by zahti** [comment]
This would be nice to have changed - completely agree.
