### ISSUE TITLE
Lunar Diplomacy Wrong Requirement

### ISSUE THREAD

**Issue by x-drea** [Zoinkwiz/quest-helper#751]
The list doesn't state that 500gp will be needed in order to craft the items requested. It only states that you'll need 400gp in the steps, which is also wrong. The Rimae asks for 500gp.

**Comment by x-drea** [comment]
<img width="238" alt="Screen Shot 2022-04-07 at 4 49 22 PM" src="https://user-images.githubusercontent.com/103222086/162325750-482aafb0-2dee-450f-bdb7-a4657a38f459.png">
<img width="229" alt="Screen Shot 2022-04-07 at 4 49 29 PM" src="https://user-images.githubusercontent.com/103222086/162325759-a0a6e997-1148-42b2-9083-f089df527259.png">
<img width="522" alt="Screen Shot 2022-04-07 at 4 50 29 PM" src="https://user-images.githubusercontent.com/103222086/162325764-3c79351b-bc50-4b80-b56f-aa1a23fa23cd.png">

**Comment by kkittle321** [comment]
Seems that you have 5 suqah hides instead of the 4. That's why he is asking for 500gp instead of 400
