### ISSUE TITLE
Mourning's End Part I

### ISSUE THREAD

**Issue by pwatts6060** [Zoinkwiz/quest-helper#752]
The Apple barrel task is on a loop with the steps updating.
![image](https://user-images.githubusercontent.com/30028569/162325152-cafd0e9e-5a7c-455e-bcaf-90a0c449867d.png)
![image](https://user-images.githubusercontent.com/30028569/162325193-d22e14e2-c14c-491c-bffe-0f9625d3e08d.png)
Trying it again now it worked but it wasn't working before and would ask you to grab another empty barrel.

**Comment by Zoinkwiz** [comment]
Fixed with https://github.com/Zoinkwiz/quest-helper/commit/0936948867fba9196a9dbba7cc43afe9926bdc5c
