### ISSUE TITLE
Mourning's End Part 2

### ISSUE THREAD

**Issue by pwatts6060** [Zoinkwiz/quest-helper#753]
Catalytic Talisman can now be used instead of death talisman. It's a reward from Guardian's of the Rift and is tradeable. Item ID: 26798
The Wiki says the Catalytic tiara does not work for this step.

**Comment by ekohvakka** [comment]
Another comment regarding Mourning's End Part 2: Add the teleport crystal to the list of recommended items for the quest.

**Comment by Zoinkwiz** [comment]
Merged fix in, thanks!

**Comment by Rerbun** [comment]
When doing this quest yesterday it still showed up red on the death altar puzzle with the Catalytic talisman in inventory
