### ISSUE TITLE
Morytania Medium Diary

### ISSUE THREAD

**Issue by merkhamill** [Zoinkwiz/quest-helper#764]
While making the Guthix balance potion for the Morytania Medium Diary achievement, the Quest Helper recognizes "Super Restore Potion" as a normal "Restore Potion" but a super restore will not work to make a Guthix balance potion.

**Comment by Zoinkwiz** [comment]
Should be fixed with https://github.com/Zoinkwiz/quest-helper/commit/952b94f1ca406e0522f68a098e6a5adea7e26c67
