### ISSUE TITLE
Exclude Jungle Herbs from Desert Easy Diary

### ISSUE THREAD

**Issue by DyonR** [Zoinkwiz/quest-helper#769]
The Herb Cleaner in Nardah can not clean Jungle Herbs, only Normal Herbs.  
For example, my Grimy Rogue's Purse herb was seen as _valid_ by Quest Helper, while this herb is invalid.

**Comment by Zoinkwiz** [comment]
Fixed with https://github.com/Zoinkwiz/quest-helper/commit/081ebcdafec1f315b1a5df2bd0d65d90cdeca7ab.
