### ISSUE TITLE
Western Provinces Medium Diary - Eagle To Feldip Hills text is incorrect

### ISSUE THREAD

**Issue by SuperNerdEric** [Zoinkwiz/quest-helper#773]
The text for the "Eagle To Feldip Hills" step in the Western Provinces Medium diary is incorrect. It says to take the eagle to the Desert area, when instead it should say take the eagle to Jungle area.

https://github.com/Zoinkwiz/quest-helper/blob/master/src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternMedium.java#L269

**Comment by Zoinkwiz** [comment]
Fixed with https://github.com/Zoinkwiz/quest-helper/commit/3c97e0a29fc161cc1baa65fbf987e74888af851d
