### ISSUE TITLE
Windows Defender identifying quest-helper as 'Severe' trojan

### ISSUE THREAD

**Issue by pwfff** [Zoinkwiz/quest-helper#777]
![image](https://user-images.githubusercontent.com/954340/166266849-ea50dbb2-51c3-4c3a-8414-ba16b51eb3db.png)

Trojan:Script/Wacatac.B!ml

Assuming it's not a legitimate match, do you know why this suddenly matched today?

**Comment by Verid** [comment]
Getting the same issues with Windows detecting it as a severe trojan as well.

**Comment by imatrojenhe** [comment]
Same here

![444444](https://user-images.githubusercontent.com/104784184/166281443-6cc3103b-2069-476d-bcc7-215cf84c4bca.png)

A post on reddit about it:

[https://www.reddit.com/r/2007scape/comments/ugs7d8/potential_runelite_trojan_windows_caught_it_this/](url)
