### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by tex808** [Zoinkwiz/quest-helper#779]
quest helper doesn't seem to be working? any ideas why?

**Comment by brody-travis** [comment]
Just taking a wild guess, but apparently the plugin is showing up as a false positive trojan for lots of people, so it could be that the developer has soft disabled the plugin until they've resolved that issue.

**Comment by tex808** [comment]
> Just taking a wild guess, but apparently the plugin is showing up as a false positive trojan for lots of people, so it could be that the developer has soft disabled the plugin until they've resolved that issue.
> 
> However, I can confirm that I also cannot use the plugin atm.
