### ISSUE TITLE
Garden of Tranquility Sequence Problem

### ISSUE THREAD

**Issue by Syphontwo** [Zoinkwiz/quest-helper#785]
If the player already has rune dust before beginning the quest in their inventory, the "Vines" section will skip straight to "use rune dust on some plant cure" and will not track any previous steps properly.

**Comment by Zoinkwiz** [comment]
Should've been resolved with https://github.com/Zoinkwiz/quest-helper/commit/7145d2e9b8fecdcc75418bfa1d9ba7fac06206fe.
