### ISSUE TITLE
Contact! doesn't progress when climbing down ladder

### ISSUE THREAD

**Issue by Netherland** [Zoinkwiz/quest-helper#786]
#### Steps to reproduce 
1. Progress quest until Explore the dungeon
2. Go down ladder east of Jex
3. Go down the trapdoor (next to the ladder you just descended from)

#### Current behaviour (bug)
Quest helper tells you to climb down the ladder east of Jex (reverts back 1 step)

#### Expected behaviour (correct)
Quest helper detects that the player climbed down the trapdoor and continues the quest as normal

#### Relevant logs and/or media (optional)
https://user-images.githubusercontent.com/3416278/167307319-c3712acb-9774-4c07-944d-7a8b759610a5.mp4

**Comment by JoshDavis97** [comment]
Also experiencing this issue.

**Comment by Netherland** [comment]
Closing this as PR #772 addresses this issue
