### ISSUE TITLE
Provide hints on when to use teleports

### ISSUE THREAD

**Issue by KaidoKarp** [Zoinkwiz/quest-helper#788]
High there, names Randy and I ain't good at a lot of stuff.
     
     Anyways, I have a suggestion to make the Quest guide a lot more idiot proof. I keep buying the suggested teleport tabs/jewelry/runes but I am to dumb to know when to use them. Its a really big difference between watching a youtuber and using the in game guide y'all have graciously made for us. I almost every time end the quest with more than half of the teleports when I use the quest helper addon. 
     I think that all you need to do is put a "   *TELEPORT TO .........." in the list of requirements. like instead of just saying "Ask the Cook at the Blue Moon Inn for a steak sandwhich" it should say "Ask the Cook at the Blue Moon Inn for a steak sandwhich *USE VARROCK TELEPORT IF AVAILABLE"

THANKS

**Comment by mattthw** [comment]
This could be better written, however I think adding teleport hints are a valid suggestion. When doing quests in an area I am unfamiliar with I am likely to have to check the wiki anyways

**Comment by Zoinkwiz** [comment]
The feature now exists in Quest Helper, it just needs adding to all existing helpers. Closing this for now for a larger issue.
