### ISSUE TITLE
Wrong Optimal Ironman quest order

### ISSUE THREAD

**Issue by KoptiKlol** [Zoinkwiz/quest-helper#790]
You need to do Architectual Alliance before you can do A Kingdom Devided but in the Ironman quest order Architectual Allience comes after A Kingdom Devided

**Comment by claudiodekker** [comment]
This is because it's a miniquest that wasn't originally part of https://oldschool.runescape.wiki/w/Optimal_quest_guide/Ironman, after checking just now this does appear to be the only miniquest that's been added to the optimal order, hence the fix PR.
