### ISSUE TITLE
Mountain Daughter Required Items

### ISSUE THREAD

**Issue by doughertyj2** [Zoinkwiz/quest-helper#798]
Mountain Daughter Quest guide does not prompt player to bring a staff or pole to the rock jump in step 2. 

A pole can be found on the ground near the farmer next to the hut you speak to the NPC in step 1. 

A staff is required in the quest helper bank tab, but it does not specify why or that it is needed in the earlier part of the quest.

**Comment by Zoinkwiz** [comment]
Should be fixed now, thanks.
