### ISSUE TITLE
In Search of Knowledge book search step has empty requirements list in overlay

### ISSUE THREAD

**Issue by Nightfirecat** [Zoinkwiz/quest-helper#806]
![Screenshot_20220603_083826](https://user-images.githubusercontent.com/2199511/171894212-4859b882-e8b5-432b-9bbb-001ca8ed0457.png)
Ideally, this requirements text should not be shown because there are no requirements.

**Comment by Zoinkwiz** [comment]
Should be fixed now, the issue was a Protect from Magic tip wasn't appearing.
