### ISSUE TITLE
Mourning's end part II - missing mirror

### ISSUE THREAD

**Issue by Rerbun** [Zoinkwiz/quest-helper#808]
Hi,

Today I did Mourning's End part II together with a friend, and we both followed the Quest helper very thoroughly I feel. Still we both ended up missing a mirror at the end of puzzle 5 part 2, making it not completable. We did not look at eachother's screen and did the puzzle completely independently, both using the quest helper.

This was especially frustrating for my friend who decided to reset, try it again, reset again when it again didn't work and then reset again to then follow the wiki instead.

For me I just went looking for a pillar with a remaining mirror on it and finished the puzzle rather quickly.

If necessary I can try to provide an image of the map with the pillar that I probably took the mirror from

This might be also related to #161, but I'm pretty sure it would be a very big coincidence if we didn't follow it correctly 3 times in total. Instead I think the helper might have a missing step for picking up an extra mirror

**Comment by MaskofAmor** [comment]
We’re you able to finish it?

**Comment by Rerbun** [comment]
> We’re you able to finish it?

Yes I was! I had to ignore the Quest helper to do so though. My friend decided to start over and follow the wiki instead

**Comment by Zoinkwiz** [comment]
I've added an icon to a pillar people kept missing removing a mirror from, so hopefully it should be better now.
