### ISSUE TITLE
Quest helper fails to distinguish between different Clue Scroll teleport scrolls 

### ISSUE THREAD

**Issue by dappersnapper456** [Zoinkwiz/quest-helper#809]
In this example, the Quest helper mistakes the Lunar Isle teleport scroll in the bank for the Nardah teleport scroll.

The result of this is that the Nardah teleport scroll is marked as white (item in bank) in the Quest helper when the player does not have the Nardah teleport scroll in any capacity

![bank](https://user-images.githubusercontent.com/39419158/172487520-3968976f-68f3-4b1d-9af1-2bb53c592bc7.png)
![helper](https://user-images.githubusercontent.com/39419158/172487213-0e642fd1-444e-4b0d-b92c-1c4920764919.png)

**Comment by Zoinkwiz** [comment]
Hey, is this for Beneath Cursed Sands? My hunch is that it's actually detecting you have a desert amulet rather than the teleport scroll.

If you click the bank quest filter button in the top right of the bank, what item is inserted for the nardah teleport slot?

**Comment by Zoinkwiz** [comment]
Hey I'm going to close this assuming ^ is correct, but if you know it's not then please feel free to comment again.
