### ISSUE TITLE
Ardougne medium diary with a few bugs

### ISSUE THREAD

**Issue by Amnesiapc** [Zoinkwiz/quest-helper#816]
I was doing the Ardougne medium diary and at first it said i needed to buy a mith grapple and when i did so the helper didn't make the icon green (sorry i'm dutch not the best one to talk in english.. xd) but now i did the hot air balloon to castle wars task and the quest won't continue even if i completed it. thats it sorry for the bad english good luck ontcijferen

**Comment by Zoinkwiz** [comment]
Should be fixed now, thanks!
