### ISSUE TITLE
[Rag and the Bone Man 2] Canifis werewolves doesn't mention Wolfbane

### ISSUE THREAD

**Issue by christopher-caldwell** [Zoinkwiz/quest-helper#824]
The text for the quest says:
> Kill the citizens/ werewolves in Canifis

I killed about 30 of them with Wolfbane before opening the wiki to see in bold that you cannot use Wolfbane lol.

Perhaps adding the same text as the wiki would be helpful to others.

**Comment by dannil** [comment]
The werewolves has an open PR #823 which fixes that part. With regards to the vultures, they don't necessarily _need_ to be, if you have high enough melee stats you can kill it before it flies away. Some clarification could maybe be good tho.

**Comment by christopher-caldwell** [comment]
Oh, okay. I searched for it in issues, but not PRs. 

re:vultures, I wasn't even able to click on them with melee. I have base 90s, not super high, but the game wouldn't even let me click on any of them. I must have been doing it wrong, but yeah a short helper would be cool.

**Comment by Zoinkwiz** [comment]
Merged in the fix, will be available for the next update!
