### ISSUE TITLE
Missing items in Cold War

### ISSUE THREAD

**Issue by doorknob60** [Zoinkwiz/quest-helper#83]
On the step where you make the Clockwork Penguin in your POH, you require a Plank and Silk in addition to the clockwork or steel bar. The plugin does not reflect this properly.

I believe it's around this line in the code:
https://github.com/Zoinkwiz/quest-helper/blob/e69a40117c10940a2b9d8970c8138e3f809dfb40/src/main/java/com/questhelper/quests/coldwar/ColdWar.java#L77

**Comment by Zoinkwiz** [comment]
Thanks for raising, added with https://github.com/Zoinkwiz/quest-helper/commit/d866f6fbb385378fdec64a7ec3d7e05f6609ceeb
