### ISSUE TITLE
Finished quests not registering 

### ISSUE THREAD

**Issue by Zombifier666** [Zoinkwiz/quest-helper#836]
Completed quests in Quest Helper are showing in the list above quests that are not started.
They do not register as completed requirements for further quests and CANNOT be clicked on to look at quest details.

First time posting and issue so I hope this is enough information. Apologies if it's not.

Thanks,
Zombifier666

**Comment by Fincap** [comment]
Due to yesterday's RuneLite and Quest Helper update, you will need to completely restart your RuneLite client. If you're launching RuneLite through the Jagex launcher, you will also need restart that (make sure it is closed from the system tray as well).
