### ISSUE TITLE
"Missing" requirements

### ISSUE THREAD

**Issue by SevenCakes** [Zoinkwiz/quest-helper#837]
The plugin still shows quests that I've done as red even though they're completed.

![Ali](https://user-images.githubusercontent.com/108411058/176450856-94d74c36-2f2f-4982-ab46-8c39f903ab35.png)
![prince ali](https://user-images.githubusercontent.com/108411058/176450891-a7a99bef-8e63-4d33-bc94-ad594955926f.png)
![little helper](https://user-images.githubusercontent.com/108411058/176450913-f255ec4b-9032-4888-9945-5ea24d36c4b0.png)

**Comment by Fincap** [comment]
Due to yesterday's RuneLite and Quest Helper update, you will need to completely restart your RuneLite client. If you're launching RuneLite through the Jagex launcher, you will also need restart that (make sure it is closed from the system tray as well).
