### ISSUE TITLE
All completed quests are back on my quest list

### ISSUE THREAD

**Issue by Stephieee123** [Zoinkwiz/quest-helper#840]
I opened up Runelite today and noticed that all of the quests that I have completed recently and ages ago have returned on my quest helper, alongside those that I have yet to complete. It highlights that because the quests are back on my list, I can no longer see the quests that I have all skills and quests done for in 'Show Meets Reqs'. It's just a big mess at the moment...

**Comment by Fincap** [comment]
Due to yesterday's RuneLite and Quest Helper update, you will need to completely restart your RuneLite client. If you're launching RuneLite through the Jagex launcher, you will also need restart that (make sure it is closed from the system tray as well).
