### ISSUE TITLE
Minor Enhancement : Law Rune Fremennik Hard Diary

### ISSUE THREAD

**Issue by PJGJ210** [Zoinkwiz/quest-helper#846]
Hard Diary item requirements does not show law run required for waterbirth teleport. This is shown in the individual step. 

First shows overall req's (no law rune)
Second shows step (does show law rune)

![image](https://user-images.githubusercontent.com/16944807/176979586-9c20a832-d7cc-4d5e-b0d4-89c36a02b286.png)
![image](https://user-images.githubusercontent.com/16944807/176979595-121f2099-c6c6-4508-a3bf-e2fe96e86de3.png)

**Comment by SpencerSKane** [comment]
This appears to have been fixed

**Comment by PJGJ210** [comment]
I can not test this but I will take your word for it.

Thanks
PJ
