### ISSUE TITLE
v1.1.5 Issue with quest sync Watchtower quest

### ISSUE THREAD

**Issue by DuceCas** [Zoinkwiz/quest-helper#85]
Hi, 

I have some problems with the quest sync of the watchtower quest,

I have already reinstalled the plugin; and have tried to use it on a difrent pc

I have v1.1.5

Thanks in advance

![Knipsel](https://user-images.githubusercontent.com/63793414/99915347-72da6800-2d03-11eb-9783-299b186d3e91.PNG)
![Knipsel2](https://user-images.githubusercontent.com/63793414/99915351-77068580-2d03-11eb-920f-985c3258bf56.PNG)

**Comment by Zoinkwiz** [comment]
Thanks for raising, this should hopefully be fixed with https://github.com/Zoinkwiz/quest-helper/commit/c9ad8bf8e9b5ce9033be87f0ac6848bfa0ca3eb7
