### ISSUE TITLE
Smiths Gloves (i) are not recognized as interchangeable with Ice Gloves

### ISSUE THREAD

**Issue by DrYoshiyahu** [Zoinkwiz/quest-helper#863]
Today I completed Clock Tower using the Smiths Gloves (i), as intended. The plugin did not treat it as valid for the quest requirements. I'm not sure what other situations this is relevant, but I know it's an issue for Clock Tower, at least.

**Comment by SpencerSKane** [comment]
Taking care of this now, I'm going to go through all the quests where this may be occurring.
