### ISSUE TITLE
Feature request: Option to automatically start quest helper when starting a supported quest

### ISSUE THREAD

**Issue by ShaunDreclin** [Zoinkwiz/quest-helper#87]

**Comment by Zoinkwiz** [comment]
I like this idea, I'll look into it and how complex it'd be to implement.

**Comment by ShaunDreclin** [comment]
I'd guess it shouldn't be too hard since there's a game message when you start quests now

**Comment by Zoinkwiz** [comment]
This should be added with https://github.com/Zoinkwiz/quest-helper/commit/8a1882d8ad445eeaf891b8ef2399fdbe9a811c97.
