### ISSUE TITLE
[Quest] [Update Needed] Mountain Daughter

### ISSUE THREAD

**Issue by Kinomora** [Zoinkwiz/quest-helper#875]
Mountain Daughter requires a staff to complete a certain part.
Previously, a Dramen Staff use to be able to be used to complete a section of this quest but it is no longer able to as its weapon type was changed.

Updates needed:
- Add Staff to the item requirement
- Note that a Dramen Staff is not supported
- Note that a Pole item can be found in the north-east of the camp nearby

**Comment by SpencerSKane** [comment]
#870
