### ISSUE TITLE
[Suggestion] Filter for Completed

### ISSUE THREAD

**Issue by absywabsy** [Zoinkwiz/quest-helper#888]
Would be cool to have a filter for completed quests only when you want to send a screenshot of all the quests you've done in one picture rather than on runescape's smaller window, you have to take a pic, scroll down, take another pic etc. and send it in bits.

**Comment by Zoinkwiz** [comment]
These days I imagine the existing wiki sync functionality for letting you share quests done would be better for this, so closing this.
