### ISSUE TITLE
The Fremennik Trials bug

### ISSUE THREAD

**Issue by Jcraig4803** [Zoinkwiz/quest-helper#914]
"talk to Swensen the navigator in his hut south west of the longhall" 
i have done his part and gotten his support via doing his maze but the quest helper is still stuck on saying the above. im having to keep a mental check list of the ones im doing after his and the flashing and point towards him is a big distraction after the fact of me completing his part. Hope this helps you debug it for others in the future.

**Comment by Zoinkwiz** [comment]
This should hopefully be resolved with https://github.com/Zoinkwiz/quest-helper/commit/1da9d6d8d6e57c294d6b200c78f133575618f662
