### ISSUE TITLE
Shades of Mort'ton Quest Helper

### ISSUE THREAD

**Issue by shureal** [Zoinkwiz/quest-helper#916]
Discovered a discrepancy with Shades of Mort'ton Quest helper.
Guide currently reccomends you bring 5000 x Coins to buy flamtaer Hammer.
Flamtaer Hammer price sold from the shop in Mort'ton is currently 13,0000
Guide does not recommend you bring money to buy the items required from the shops in Mort'ton
IE olive oil, timber beams, limestone bricks, swamp paste

Problem occurred because I had purchased the hammer before hand for a similar price to prepare for the quest
(Something that is commonly done at the GE by people using the pluggin)

End Problem: Since there was no other requirements for coins other than the hammer, player was misled into believing they did not require any more coins for other purchases after traversing the entire swamp and finding out that they needed coins on hand to continue the quest.

Suggestion: Add a second separate coin requirement for the items you need to buy to complete the quest.
Suggestion: Update the current price of "Flamtaer hammer" to the correct current price at the shop.
![suggestedcoins](https://user-images.githubusercontent.com/112574433/187736077-e3f39cb0-d4e1-4e49-b69a-3b26d0cbd0ea.png)
![actualprice](https://user-images.githubusercontent.com/112574433/187736086-5a4307f4-a43b-4632-b12d-f0fde7dfec39.png)
![moneyididntbring](https://user-images.githubusercontent.com/112574433/187736089-d7979a69-2af2-4ff7-ae11-53dec3318d50.png)

**Comment by Zoinkwiz** [comment]
I think there's been a misreading of the requirement there, the requirement says:

- 5000 coins,
This is to be used for the items

- more if you want to buy a Flamtaer Hammer
This indicates you'll need more money for the hammer

I'll add the specific price to that rather than just 'more'.
