### ISSUE TITLE
Merlin's Crystal Bug

### ISSUE THREAD

**Issue by XselenS** [Zoinkwiz/quest-helper#919]
During the phase "Get Excalibur" once you speak to the lady at the Lake the quest que will not progress. You are tasked to go to Port Sarim jewelry store and give the beggar that appears bread.

The quest helper will remain on the "Speak to the lady of the Lake" task until you go to the jewelry store. Once you go to the store it will progress properly again.

**Comment by Zoinkwiz** [comment]
Response in https://github.com/Zoinkwiz/quest-helper/issues/940
