### ISSUE TITLE
Add a vertical offset to the 'Use Item' overlay

### ISSUE THREAD

**Issue by ShaunDreclin** [Zoinkwiz/quest-helper#92]
Right now the overlay covers up the object, it would look nicer if it was hovering above it instead
![Screenshot ](https://user-images.githubusercontent.com/5851433/100152030-1052aa80-2e70-11eb-9f0c-9f4ed0cec472.png)

**Comment by Zoinkwiz** [comment]
I've changed the scaling of the icon to be less massive, can be removed, and looks less like it should be above the object now. For now I'll keep it on the object, as it can get problematic to have it above larger items.
