### ISSUE TITLE
Murder Mystery bug

### ISSUE THREAD

**Issue by broagent007** [Zoinkwiz/quest-helper#93]
Quest helper is infinitely stuck on wanting to coat the criminal's dagger with flour, or picking up silverware from top floor manor barrel.

**Comment by Zoinkwiz** [comment]
Hey, hopefully https://github.com/Zoinkwiz/quest-helper/commit/477ce2e3b1f665e5adb92b7eb04621e107d4bb4a should fix that once it's live.
