### ISSUE TITLE
Redo the Legend's Quest

### ISSUE THREAD

**Issue by HyperAlch** [Zoinkwiz/quest-helper#937]
I'm sorry, but who ever did the Legend's Quest for this plugin needs to go back and try again. THE HELPER FOR THIS QUEST IS THE WORST ONE IVE HAD TO DEAL WITH. 

So many items missing from the requirements side panel. 

Make my way back to the jungle, OOPS CANT GO IN, YOU FORGOT "Radimus notes" even though it doesn't list it on side panel LIKE EVERY OTHER QUEST IN THIS PLUGIN.

Cool, now I'm back, OOPS FORGOT THAT HOLLOW REED I THOUGHT I WAS DONE WITH. Why in the world would I think I was done with the reed? OH, I KNOW BECAUSE IT DOESN'T LIST IT AS A REQUIREMENT UNTIL AFTER IVE SPENT 5 YEARS CHOPPING MY WAY INTO THE JUNGLE.

Requirement: Runes for charging orb spell? WHICH ONE?!?!? THERES 4! IF IT DOESN'T MATTER WHICH ONE, MAKE IT CLEAR.

I can go on and on, the point is ever since I've started using this plugin I have NEVER had to use outside guides and videos to try and figure things out, because the plugin generally makes everything clear. Not this time, I've had to use both video guides AND written guides. Also, ever since using this plugin I've never had to spend 10 minutes returning to the bank because I forgot something LET ALONE 4 SEPERATE TIMES. 

The Legend's Quest portion of this plugin lacks the quality and ease of use that this plugin is known for. Until it gets redone ill be telling my whole Discord not to use the plugin for this quest and stick with the time and battle tested method of just using a video guide. Not to spite your team or the hard work you have done, but because I truly believe that the quest helper for this particular quest needs a rework so badly that its easier not to use it.

**Comment by Zoinkwiz** [comment]
Hey, so I've checked, every sidebar section aside from the starting off one (where you're in the Legends' Guild) has the Radimus Notes in it.

Each section which requires the tall reed does require the machete, and has a step to use the machete on the reeds for a new one.  If you can specify a section where that's not the case please let me know so I can fix it.

I've updated the charge orb spell text to be 'Runes for any charge orb spell you have the level to cast'. (a19b1403)

If you can go on and on, please do so said issues can be resolved.
