### ISSUE TITLE
quest helper plugin only showing 2 minquests and no quests

### ISSUE THREAD

**Issue by Mok101** [Zoinkwiz/quest-helper#94]
hi there basically i've just gone to check my quest helper plugin and 2 miniquests are the only ones that shows up no quests shows up amongst the list please help
![questhelperplugin problem](https://user-images.githubusercontent.com/69005922/100326929-8135c600-301a-11eb-96f1-a379202d0703.png)

**Comment by Zoinkwiz** [comment]
Hi @Mok101 , have you done all the quests and miniquests besides those two? If so the helper only shows things you've yet to complete so this'd be expected behaviour. If not, let me know.
