### ISSUE TITLE
Lumbridge Hard Diaries missing a requirement.

### ISSUE THREAD

**Issue by FiveNine** [Zoinkwiz/quest-helper#941]
In the Lumbridge Hard Diary helper, the Bones to Peaches task says you need:
- 60 Magic
- Bones to peaches unlocked
- 1 x bones
- 4 x Water rune
- 2 x Nature rune

It also requires 4 x Earth runes.

Just a minor issue I thought I should report. 😄 

![image](https://user-images.githubusercontent.com/62566993/194556561-11f09edc-3ab8-449b-a4c3-75e3bb550ab9.png)

**Comment by Zoinkwiz** [comment]
Fixed in https://github.com/Zoinkwiz/quest-helper/commit/c61dc6545af2224016f46eb834a477ae15444d31
