### ISSUE TITLE
Sins of the Father: Vanstrom Attack Counter PLEASE

### ISSUE THREAD

**Issue by Hjodir** [Zoinkwiz/quest-helper#943]
I cannot manually count his attacks and fight him at the same time.  There is too much going on in this fight for me to focus on counting and fighting at the same time.  So it would be really really helpful if this addon would just count his attacks for me and prompt me to move away on the 7th attack.

**Comment by Zoinkwiz** [comment]
Hey @Hjodir , unfortunately we can't add anything which will help directly with boss fights, per the [3rd party guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1).

Specifically: `Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper.`
