### ISSUE TITLE
Demon Slayer Rovin's Key

### ISSUE THREAD

**Issue by TheAngriestPasta** [Zoinkwiz/quest-helper#944]
On the quest speedrun worlds, I reset demon slayer and right click it in my journal to start quest helper.

It still thinks I have Rovin's Key from my previous speed run attempt. It will not give me the option to un-check the completed checkbox. I have not found a way to reset it and have even uninstalled the plugin and reset to default settings. Logged off and hopped on and off my main too didn't help.

This is annoying because the plugin will not tell me the correct dialogue tree when speaking to Rovin.

**Comment by Zoinkwiz** [comment]
This will be fixed by https://github.com/Zoinkwiz/quest-helper/pull/1447.
