### ISSUE TITLE
The Fremennik Isles - missing requirement

### ISSUE THREAD

**Issue by joeamansfield** [Zoinkwiz/quest-helper#956]
In the general requirements for The Fremmenik Isles it is missing the 46 crafting requirement for ironmen, despite having the 56 woodcutting requirement.

**Comment by Zoinkwiz** [comment]
Fixed in [f2ba5a732ffb9cfb8456bff7320b0fa2f3bde486](https://github.com/Zoinkwiz/quest-helper/commit/f2ba5a732ffb9cfb8456bff7320b0fa2f3bde486)
