### ISSUE TITLE
Throne of Miscellania breaks if you switch who you wish to marry

### ISSUE THREAD

**Issue by Madmosh** [Zoinkwiz/quest-helper#963]
I accidently choose the wrong character and when I switch the quest plugin stopped working for only the Throne of Miscellania quest. I am unable to open it too see the requirements and next steps etc. Tried relogging and restarting and that did not fix the issue. 

I unfortunately have no way to test if the act of switching was what caused it to break, But once I switch the quest stopped updating in the plugin, after closing the quest I was unable to open it again.

**Comment by Zoinkwiz** [comment]
This should be fixed with the next release.
