### ISSUE TITLE
Problem with Royal Trouble

### ISSUE THREAD

**Issue by mpalssonur** [Zoinkwiz/quest-helper#964]
The directions for Royal Trouble won't open when it is clicked in the list. The plugin exhibits strange behaviour after trying.

I just finished the Throne of Miscellania quest taking advantage of the new diversity changes to romance Astrid as a female character. This caused some strangeness in the quest helper walkthrough but once I got to the favour part at the end of the quest everything seemed to be working again. Then I started Royal Trouble but when I went to open the guide for the quest from the quest list nothing appeared to happen. 

I then went to open up the configuration tab to start troubleshooting but after opening it quest helper reopened almost immediately.

When I tried to close quest helper it just reopened.

I quit runelite and relaunched it and everything worked fine. I could open and close quest helper just fine and the other quests I tried opening up worked. I then tried Royal Trouble and the previous behaviour repeated itself.

Logging out and logging back in had the same effect as quitting and relaunching.

**Comment by Zoinkwiz** [comment]
This should all be fixed with the next release.
