### ISSUE TITLE
Recruitment Drive no longer requires you to be female

### ISSUE THREAD

**Issue by bwbuhse** [Zoinkwiz/quest-helper#965]
The Sir Leye step has been updated and now your character's gender is irrelevant. You need to choose the correct weapon based off what you get told, i.e. "No blade will harm him" or something like that is the warhammer.

**Comment by zahti** [comment]
As of **9 Nov 2022**, with the Diversity & Inclusion update for OSRS, being a female is no longer a requirement for completing this quest ([SOURCE](https://oldschool.runescape.wiki/w/Update:Diversity_%26_Inclusion_Changes_and_Quest_Speedrunning_Updates))
- 'You need to be female' general requirement needs to be removed.
- The 3000gp item requirement needs to be removed.
![image](https://user-images.githubusercontent.com/38710634/204122035-61ab93a2-30ef-4519-874d-e17a5095c58e.png)

**Comment by zahti** [comment]
I just added another issue here: https://github.com/Zoinkwiz/quest-helper/issues/976
