### ISSUE TITLE
Throne of Miscellania bugged.

### ISSUE THREAD

**Issue by EliJ91** [Zoinkwiz/quest-helper#970]
The quest helper doesnt start everytime and sometimes it freezes the side panel and I cant select anything else in the side panel. It will force open quest helper side panel if i try to open anything else in the side panel. 

Edit: it seems to be only Throne of Miscellania

**Comment by ecoat-nick** [comment]
I just ran into this exact same issue. It seemed to be running fine at first, then when I exited the game and attempted to restart Throne of Miscellania Quest Helper it is stuck in this loop you described. I am able to get out of the loop by switching to another quest in the Quest Helper interface. 

I am unable to start the quest helper at all for this quest anymore.

**Comment by Zoinkwiz** [comment]
This should be fixed with the next release.
