### ISSUE TITLE
Throne of Miscellania Romance Issue

### ISSUE THREAD

**Issue by traddmccorkle** [Zoinkwiz/quest-helper#992]
In Throne of Miscellania, if you're a male character and choose to romance the prince, the quest helper doesn't offer you the steps for the prince, and offers you the steps for the princess. I'm guessing the code checks for your character's gender, but Jagex recently updated the quest with the inclusivity update I believe.

**Comment by Zoinkwiz** [comment]
This should be resolved in https://github.com/Zoinkwiz/quest-helper/commit/b689ec35e4190fbaea10abe78adff59e3659c0ae.
