### ISSUE TITLE
downloaded runelite, cant access quest helper

### ISSUE THREAD

**Issue by ember100** [Zoinkwiz/quest-helper#994]
i downloaded runelite and cant figure out how to get quest helper on there. if i could get some help with this i would really appreciate it. thanks.

**Comment by labofsinan** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/115546292/206259625-a14a960f-8bc1-4ae4-a41b-0b57e773e753.png">

<img width="452" alt="image" src="https://user-images.githubusercontent.com/115546292/206259855-c4940cc6-6ec3-4ee1-8717-b797cdb6509b.png">

Basically you need to install it from plugin hub.

Steps

1. Click the settings icon in Runelite.
2. Click plugin hub.
3. Search for the quest helper plugin in the search bar.
4. Finally, install the quest helper plugin.

Hope this helps!
